### ISSUE TITLE
 Fagalicious - GENF  :: FFProbe Error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vampirelayer** [CodyBerenson/PGMA-Modernized#100]
I'm getting a few of the above when matching certain titles, mostly happening in Fagalicious.

Just to name a few:
`https://fagalicious.com/raging-stallion-bruno-bernal-michael-roman-pierce-paris-hot-threeway-gun-show/
https://fagalicious.com/raging-stallion-tegan-zayne-woody-fox-riley-mitchell-teddy-torres-three-wishes-gay-porn/
https://fagalicious.com/raging-stallion-tex-davidson-ace-era-teddy-torres-erectus/`

**Comment by CodyBerenson** [comment]
@jph71 I get the same result.  Here is the log when you take a look.


[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6478466/com.plexapp.agents.Fagalicious.log)

**Comment by JPH71** [comment]
I will look at it tonight!

**Comment by CodyBerenson** [comment]
@vampirelayer 

@JPH71 made a fix to the agent for the above titles.  I've tested it against the above titles and the most recent 15 Fagalicious titles and 100% match.  I'll push the fix momentarily.

Note:  the FFProbe Error is unrelated.  The agents have a routine to match against duration so that the proper movie and not scene is matched on IAFD.  It isn't uncommon for a studio to have the exact same name of a movie and scene, and when the agent incorrectly matches the scene, it won't provide full actor roles, etc. from IAFD.  For duration matching to work, one must have FFMPEG installed.  Duration matching is not required for scene matching and is disabled when the FFProbe error occurs.  So, you're logs will always contain FFProbe Errors while your agents continue to properly match.

**Comment by JPH71** [comment]
@vampirelayer <https://github.com/vampirelayer>
Hi all, the comment Cody made about FFProbe is absolutely correct - Install
FFMPEG for this functionality until I can find a way to get Plex to return
the media duration....
The most obvious way does not work.... grrrr...

Jason
