### ISSUE TITLE
Fagalicious - some titles don't match

### ISSUE THREAD

**Issue by vampirelayer** [CodyBerenson/PGMA-Modernized#102]
I will share the log files if you can't replicate them.

`https://fagalicious.com/falconstudios-paddy-obrian-wrecks-edin-sols-smooth-plump-buns-with-his-beer-can-cock-in-sun-kissed/`

`https://fagalicious.com/ragingstallion-jessy-ares-and-landon-conrad-pound-each-other-in-the-woods-part-2/`

`https://fagalicious.com/belami-summer-break-orgy-marcel-gassion-ariel-vanean-andre-boleyn-marc-ruffalo-rhys-jagger-part-1/`

`https://fagalicious.com/belami-summer-break-orgy-marcel-gassion-ariel-vanean-andre-boleyn-marc-ruffalo-rhys-jagger-part-2/`

**Comment by JPH71** [comment]
I will need to look into the search string to focus the search and make it
less generic as the first *(Falcon Studios) - Paddy O’Brian wrecks Edin
Sol’s smooth plump buns with his beer can cock in “Sun Kissed” (2013)* did
not match as Paddy O'Brian is in tonnes of scenes and the resultant search
string came back with this Search Query:
https://fagalicious.com/search/paddy+o

The second.. The main picture for the second is just a normal jpeg... no
front cover artwork on fagalicious:
*(Raging Stallion) - Jessy Ares and Landon Conrad pound each other in “The
Woods Part 2” (2013)*

The third and fourth matched and Plex did its little bit to help with
matching titles with the word *"Part"* and combined them as 1 film

*(BelAmi) - Marcel Gassion’s birthday orgy with Ariel Vanean, Andre Boleyn,
Marc Ruffalo and Rhys Jagger in “Summer Break, Episode 4” (Part 1) (2017)*

*(BelAmi) - Marcel Gassion’s birthday orgy with Ariel Vanean, Andre Boleyn,
Marc Ruffalo and Rhys Jagger in “Summer Break, Episode 4” (Part 2) (2017)*

In relation to the 3rd and 4th, when I have a whole film split into scenes
and an admixture of 720p and 1080p which prevents you merging them together
using mkvToolKit - I generally do the following:

*(Studio) - Film Title (Year) - Part 1.mp4*
*(Studio) - Film Title (Year) - Part 2.mp4*
* (Studio) - Film Title (Year) - Part 3.mp4 *
* (Studio) - Film Title (Year) - Part 4.mp4    *


Plex automatically matches them and combines them into one film on the grid.

In this case as the *Part 1* was before the *(YEAR)* it combined them and
also had the Part 1 in the Title... but there is no other way around this
as the code stands.

here is the proof of the pudding:
[image: image.png]

Jason

**Comment by CodyBerenson** [comment]
I received the same results as Jason.  Log attached for troubleshooting the falcon file.  

1.  Falcon title won't match.  Paddy is a personal favorite, so I'd make this the priority over anything else possible, even including work.
2. Raging Stallion title matches fine.  
3. & 4.  My plex mergered the two titles into one and matched it.  

From my perspective the bug here is #1, here's the log.  @vampirelayer if you weren't able to get the Raging Stallion or BelAmi titles to match, you're going to need to uploard your logs, as neither Jason nor I can replicate. 

@JPH71 In case you need it, here's the log for the Falcon title

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6524226/com.plexapp.agents.Fagalicious.log)

Jason's pudding pic didn't come thru for me, so just in case, here's the proof in the jello:

![image](https://user-images.githubusercontent.com/40373801/119178311-86a92180-ba3b-11eb-80c5-21bce810616c.png)

**Comment by vampirelayer** [comment]
Thanks @CodyBerenson
The Raging Stallion one finally matched.
Still no luck with the BelAmi one. I attached the log.
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6527704/com.plexapp.agents.Fagalicious.log)

**Comment by j-ktz** [comment]
Having issues with these 3 titles on Fagalicious:

(Sean Cody) - Brysen and Dax flip fuck bareback (2021)
(Falcon Studios) - Cole Connor bangs Felix Fox raw in “Making the Grade” (2021)
(Falcon Studios) - Cole Connor bangs Felix Fox raw in “Making the Grade” (2021)

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6833155/com.plexapp.agents.Fagalicious.log)

**Comment by JPH71** [comment]
Hi guys,

Sorry for not been as attentive as usual but my new role has me doing
60-70hrs per week lately
Next week I am off the whole week, so will dedicate some time to the title
matching routine...
Send me a list of all the films you are having issues with as these help me
with perfecting the routine.
And in J-ktz since you are using a MAC please send the log files too,
making sure that each log file is per title you are matching.

If any of you are using a linux based system this also applies to you...

Sorry for the delay but 12 hour shifts alternating every two days are a
right bummer...

Hope you are all keeping well

Jason!

**Comment by j-ktz** [comment]
@JPH71 Ahhh, hang in there. That sounds brutal. Sorry about the log. Here are the correct ones. Let me know if you need anything else. Get some rest! 
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6833528/com.plexapp.agents.Fagalicious.log)
[com.plexapp.agents.Fagalicious-2.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6833529/com.plexapp.agents.Fagalicious-2.log)

**Comment by CodyBerenson** [comment]
@j-ktz 
Hey youngin',

@jph71 has made a fix to fagalicious that fixes the above two titles you mention.  I'm bundling up a release now and will post it soon.  I'll close this issue in a couple of days.

Cheers!

**Comment by j-ktz** [comment]
Awesome. Thanks boys! I'll test and report back. @JPH71 @CodyBerenson
