### ISSUE TITLE
Fagalicious is not matching scenes anymore?

### ISSUE THREAD

**Issue by vampirelayer** [CodyBerenson/PGMA-Modernized#107]
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6852897/com.plexapp.agents.Fagalicious.log)

Affected scenes are:
https://fagalicious.com/timtales-tim-kruger-fucks-benjamin-king/
https://fagalicious.com/belami-kevin-warhol-bottoms-vadim-farrell-kris-evans/
https://fagalicious.com/falcon-studios-cole-connor-felix-fox-making-the-grade/

**Comment by CodyBerenson** [comment]
@jph71 I get the same results.  Fagalicious seems to have stopped working.  Will you take a look, please?

**Comment by JPH71** [comment]
will do...

**Comment by JPH71** [comment]
Starting to look at faglicious now!

**Comment by j-ktz** [comment]
Bless you, King. 👑 

On July 30, 2021, GitHub ***@***.***> wrote:
> Starting to look at faglicious now!
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CodyBerenson/PGMA-
Modernized/issues/107#issuecomment-890060245>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5RC6PQ2LZPY4IAH2G23T2LR7JANCNFSM5AXFRJOQ>.

**Comment by CodyBerenson** [comment]
@vampirelayer @j-ktz 
Hello gents.  @JPH71  has made the fixes to Fagalicious and I've tested.  I'm bundling the agents up in a new release now.  Please be on the lookout.  I'll leave the issue open for a couple days after the release and then close it out.

Cheers

**Comment by vampirelayer** [comment]
This is working now! Thanks.

**Comment by j-ktz** [comment]
Can't speak to @vampirelayer's issue, but I threw a bunch of titles at it and it worked for me!
