### ISSUE TITLE
Waybig matching issues

### ISSUE THREAD

**Issue by ScoBoXxX** [CodyBerenson/PGMA-Modernized#110]
I have been noticing some issues with pulling poster artwork lately.  It seems random and only for scenes so far, and specifically to Waybig matches I think.  Some work fine, others don't.

The following examples are not pulling the posters/artwork.  They seem to match OK but just not pulling poster.  Description and actors and IAFD icons are all there just no images.

(Helix Studios) - Keagan Case Bottoms For Silas Brooks (A.K.A. Baconator) In “Beach Bums - Florida, Part Two” (2021)
URL: https://www.waybig.com/blog/2021/08/12/helix-studios-keagan-case-bottoms-silas-brooks-baconator-beach-bums-florida-part-two/

(CockyBoys) - Carter Dane RETURNS To Camp CockyBoys And Bottoms For Leo Louis (2021)
URL: https://www.waybig.com/blog/2021/08/12/cockyboys-carter-dane-returns-to-camp-cockyboys-and-bottoms-for-leo-louis/

Thanks for everything you do here!  This PGMA-Modernized agent is AMAZING!  My PleXXX collection is on a while new level now thanks to this!

**Comment by CodyBerenson** [comment]
Hello @ScoBoXxX !!

Glad to hear the agents are working out for you!  I did just test both of these examples, and they return the artwok fine for me:  

![image](https://user-images.githubusercontent.com/40373801/129415305-f1ba21b6-c537-4381-b47b-3e7ab15ba1e4.png)

@jph71 probably will need to see the WayBig log when it happens again, since I'm not able to replicate it.  :(

Questions:  

1. Where approximately are you geographically located.  I think non US folks may have some issues with the thumbor imaging service....for example, @jph71 in in Europe and has issues with our Thumbor service
2. Do you use a VPN?  You may want to if you have the ability, we've had some folks that had better poster image performance when using a VPN
3. Have you tried to Fix Match to see if the image is retrieved when it rescans?
4. Have you tried changing the pause in the WayBig settings?  Sometimes sites perceive denial of service and we added the pause for just such an issue.  If you do try changing this pause, remember that you will need to kill your PMS and then restart it.
![image](https://user-images.githubusercontent.com/40373801/129415952-af8c1389-3166-4328-8d0c-18b2d514167a.png)

Sorry can't be of more help.

**Comment by ScoBoXxX** [comment]
I am in the US.  This has been working great for me for a long time.  Just recently this issue has come up.  I just dl a few more files and they are not matching properly either.  This started after I updated the agents.  I will try to re-do the agent setup from scratch and see if that helps.

Where can I find the Waybig log?

**Comment by CodyBerenson** [comment]
@jph71 would you look at the log please and see if anything seems out of sorts?

@ScoBoXxX as a workaround, not ideal I know, but you can use the thumbor code inline to bring a cropped poster:

1. in notepad, paste the thumbor link:  http://34.86.184.21:8888/unsafe/0x0:800x1200/
2. right click on the poster in waybig and copy link
3. append it to the end of the above link
4. copy all of it as the poster URL in plex for that specific title
5. plex will pull in the properly cropped poster from WayBig via the Thumbor service

**Comment by ScoBoXxX** [comment]
All of that works fine.  I went through the logs (I am by no means qualified to do so lol) and I found this URL for the thumbor service: **http://35.232.232.183:8888/unsafe/0x0:800x1200/**https....etc
Since my memory fails me I have to assume that I piece-mail updated the agent plugins and somehow this URL was never updated.  I'm going to delete and reload all the agent plugin folders and see if that resolves it.

**Comment by CodyBerenson** [comment]
@ScoBoXxX 
Please download and install the latest agents. This address was updated a couple weeks ago (issue #109).  Please remember to completely kill your Plex media server, and then restart it. You can double check that the address is correct in the settings for each of the scenes agents.

![image](https://user-images.githubusercontent.com/40373801/129456721-3be0b4b5-11d6-4bb5-9d53-2b3beb66d79f.png)

**Comment by ScoBoXxX** [comment]
That'll be the last time I piece-mail my agent updates :)
Seems to be working better now.  Thanks!
