### ISSUE TITLE
Matching Issues w/ " - " in IAFD Title

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#152]
Seeing issues with matching EastBoys titles on IAFD - they contain " - " (space dash space) in the IAFD title.

When using the title as shown on IAFD, PGMA is dropping part of the title and not able to return a match. When the title is modified to (space dash), PGMA passes through the title as expected, but does not return a match as IAFD is looking for an exact match on the (space dash space).

Title: (EastBoys) - Young Workers - Bareback (2018) - [Benjamin Daniels Palmer]
IAFD: https://www.iafd.com/title.rme/title=young+workers+-+bareback/year=2018/young_workers_-_bareback.htm
Log: [IAFD - Title Loss with dash.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8415124/IAFD.-.Title.Loss.with.dash.txt)

Title: (EastBoys) - Earl Bryant - Casting (2020)
IAFD: https://www.iafd.com/title.rme/title=earl+bryant+-+casting/year=2020/earl_bryant_-_casting.htm
Log: [IAFD - Title Loss with dash 2.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8415193/IAFD.-.Title.Loss.with.dash.2.txt)

**Comment by JPH71** [comment]
Thanks for highlighting this - I will sort it out!

**Comment by JPH71** [comment]
@jocklover 
I have sorted out the issue - and tested it with the above title **(EastBoys) - Young Workers - Bareback (2018) - [Benjamin Daniels Palmer]**. Please note that as you are including the cast in the filename, you should delimit the cast names so that the resulting tiles looks like this **(EastBoys) - Young Workers - Bareback (2018) - [Benjamin Daniels, Palmer Lewis]** - note the comma between the actors' names.
In this case the mistake may not have caused an issue as the agent would get the cast of the page... but if using a different agent like waybig it would have searched for a single actor called Benjamin Daniels, Palmer

I will forward the code to Cody to upload to the repository after he has thoroughly tested it.... 

You could help in the meantime; try a number of titles with dashes, colons and plain... to check that I have not broken the original functionality... rename your original utils.py in the IAFD bundle folder then put the attached file into  **_C;\Users\[Your Profile Name]\AppData\Local\Plex Media Server\Plug-ins\IAFD.bundle\Contents\Code_** if you are a windows user.... then remove the .txt extension

[utils.py.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8516427/utils.py.txt)

**Comment by jocklover** [comment]
I have tested the impacted cases and the issue is resolved. I have not done a deep dive on collateral testing. I will follow up if I do find anything.
Thanks again for the work on this.
