### ISSUE TITLE
Can't get the Scenes agent to return any matches

### ISSUE THREAD

**Issue by mhunter8** [CodyBerenson/PGMA-Modernized#16]
Not having any problems with the Films agent, but I've tried any number of combinations in naming scenes but nothing seems to work.  Doesn't seem to matter what studio I try.  I've even gone so far as to go directly to the waybig site and copy what they have, and that doesn't work either.  I'm probably missing something but can't seem to figure it out.  

For example, here are three different websites for the scene:
https://www.gayeroticvideoindex.com/E/23393.html
https://www.waybig.com/video/american-in-prague-2019-blake-mitchell-scene-one-bel-ami-online-433595.html
https://fagalicious.com/belami-blake-mitchell-is-an-american-in-prague-eluan-jeunet-andrei-karenin-bareback/

What would be a way to name this file to get it to find something.

The above is just one example.  As I mentioned I can't get any scenes to work.

Thanks!

**Comment by CodyBerenson** [comment]
@mhunter8 
Hello!  Welcome to PGMA. :)

This may sound a bit confusing, so excuse me if I ramble while I break this down.  

Re:  Your first link:  The GEVI Agent only scrapes films, not scenes.  Sorry.

Re:  Your second link:  The WayBig Agent won't scrape **videos** from waybig, only Blog entries.  You're in luck, this same **video** also has a Blog entry on WayBig, here:

https://www.waybig.com/blog/2019/11/18/bel-ami-blake-mitchell-eluan-jeunet-andrei-karenin-an-american-in-prague-blake-mitchell/

Therefore, using the naming convention (Studio) - Title (Year).ext the  proper filename to be picked up by the WayBig Agent should be:  

(Bel Ami) - Blake Mitchell, Eluan Jeunet and Andrei Karenin in ‘An American In Prague: Blake Mitchell, Scene 1’ (2019).ext

Re: your third link, this is a perfectly scrapable blog entry to be picked up by the Fagalicious Agent with the properly named file:

(BelAmi) - Blake Mitchell and Eluan Jeunet fuck Andrei Karenin bareback in “Blake Mitchell is An American in Prague”.ext

Its important to remember that you have to use the studio as the blog displays it to you.  Often, within the same blog different scenes may be Bel Ami, BelAmi, Bel Ami Online, BelAmiOnline.  Use verbatim as the blog presents it.  

Final note:
This exact same scene is also carried on the 3rd blog site, QueerClick.  To be picked up by that agent, It should be properly named

(BelAmiOnline) - Blake Mitchell, Eluan Jeunet and Andrei Karenin – Blake Mitchell is An American in Prague.ext

Hope this helps.  If you have challenges, let us know...., 

Cheers,

Cody

**Comment by JPH71** [comment]
@mhunter8
Welcome... one other thing to note if a title has a Colon in it - you can replace that with a space-dash-space sequence as colons are not allowed in filenames...

so 
`(Bel Ami) - Blake Mitchell, Eluan Jeunet and Andrei Karenin in ‘An American In Prague: Blake Mitchell, Scene 1’ (2019).ext`

becomes:
`(Bel Ami) - Blake Mitchell, Eluan Jeunet and Andrei Karenin in ‘An American In Prague **-** Blake Mitchell, Scene 1’ (2019).ext`

Also a quick favour - if you come across a blog or VOD/DVD site that has loads of content and especially poster artwork - let us know and we can hopefully create an agent for it....

Kind Regards
J

**Comment by JPH71** [comment]
@mhunter8
One more thing as CodyBerenson has mentioned in the ReadMe try and keep your scene Libraries separate from Film libraries. As there are over 10 agents under the combines GayAdult - it takes longer to process each title in the library.....

**Comment by mhunter8** [comment]
@CodyBerenson @JPH71 Thanks guys!  I pulled the latest updates and also am using exact matches which is helping quite a bit.  One thing I noticed with having separate libraries is that if you click on the actor it only returns matches for that particular library - which is kind of a drag.  I know you can type in the name in the general search engine which will return all libraries.  That's a plex issue however and I don't think there is much you can do about it.  

One more question, when setting up the agents for Gay Adult, Gay Adult Scenes and Gay Adult Films the description mentions it utilizes different sources.  Are those sources always used or do you need to also manually check the sources you want those agents to use?

**Comment by CodyBerenson** [comment]
@mhunter8 
Really glad its working for you.  I hope I am understanding your question correctly...if I completely miss the mark please let me know.  For any given set of agents, you choose which sources and the priority that it uses.  Let's say that 90% of your content matches from AEBN; certainly choose AEBN and rank it first.  Once Plex finds a match, it stops, and it won't continue working its way down the priority list.  

In the figure below, I'm currently testing an update to GEVI, so you can see that it is the only agent I have selected.  If, for example, a film doesn't isn't indexed on GEVI but is on AEBN, in this example Plex won't match it because the AEBN agent won't fire off.  

![image](https://user-images.githubusercontent.com/40373801/80850851-2fe06800-8bec-11ea-98e1-ea796dacb19a.png)

Since five different indexing sites could index any given film slightly differently (e.g., the name of the studio, punctuation in the title of the film), you really should drag your preferred indexing sites higher in the priority list...Priority is important...it will save your computer processing cycles by not making calls to an index that isn't one of your go-tos.

Is this what you were asking about or did I have a cocktail too many tonight?

p.s.  good observation about the pros...and obvious cons...of separate libraries.  that's why @JPH71 created the Gay Adult grouping of Agents (for content cominglers) and the Gay Adult Films and Gay Adult Scenes for (for separatists).   The downfall of comingling, though, is that the larger the library grows, the longer Plex takes to scan.

**Comment by mhunter8** [comment]
@CodyBerenson Yep, that answers the question.  I was getting confused by reading the information for the three main agents.  The message says that the "... metadata that contributes to this agent comes from the following websites ... blogs ..."  You might want to change the wording so it clarifies that in order for a particular site to be searched, it must be selected.  If it isn't selected, it will be ignored.  I completely understand now, but for new people it might avoid some confusion.
