### ISSUE TITLE
[BUG]: WayBig Release Testing Agent Creating Extraneous Collections

### ISSUE THREAD

**Issue by dodecaphone** [CodyBerenson/PGMA-Modernized#196]
# Mandatory #

## Describe the bug: ## 
When matching videos, the agent is creating a set of odd collections which need to be manually deleted. These include things like "|(tilde)| Not on IAFD" and "|(tilde)| WayBig" - _The tilde is messing up the formatting so I changed it to the word tilde._

## Specific Agent(s) Causing the Issue: ##
WayBig

## Index Site URL(s) Attempting to Match: ##
N/A

## Log Attached: ##
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/9603383/com.plexapp.agents.WayBig.log)

# Optional #

## Screenshot(s) with all nudity redacted: ##
![Untitled](https://user-images.githubusercontent.com/20006508/191149822-b4c442b6-88a9-4d7e-bb57-b7496bc011e5.png)

## Desktop (please complete the following information): ##
 - OS: [e.g. iOS] Windows 10 Pro
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 104

**Comment by JPH71** [comment]
Hi @Sam

This is not a bug
We are improving on the agents at the moment.
So that Users can see what movies have been scraped by which agent |~|
Waybig - means that WayBig was used to scrape the agent.
If you delete the collection, Plex will by design lock the metadata fields
of the movies that have this collection and prevent these fields being
updated.
To unlock these fields you will have to go into the library, select all the
films, click on the edit film button, go to tags, and click on lock
collection, followed by unlock to make sure all films have this field
unlocked. Otherwise future scrapping will not affect/change the contents.

You will find other default collections now created these include:
|~| On IAFD
|~| Not ON IAFD - when scraping this film was not found on IAFD
|~| Stacked - Film is split into parts, discs, scenes etc
|~| Not Stacked
|~| Compilations

There are others like
|a| - for actors
|c| - countries
|d| - directors
|s| - Studio

The reason this was done was to group collections. So when you go into the
Collections of a library - you have all the collections in order of type
rather than just alphabetised.
In the current version - if you turn Collection Grouping in the preferences
OFF, these should disappear and will be replaced by the wording after |x|,
these means that your collections appear in alphabetical order, all jumbled
up

I am currently working on hiding the |~|, this should be soon completed - I
am awaiting some help on how to change an actor's picture in the cast
collection. And getting help from @Joca with the testing.

Once this is done All should be well.

Jason xxx
