### ISSUE TITLE
Create new AdultDVDMarketplace Agent

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#2]
AdultDVDMarketplace, https://www.adultdvdmarketplace.com/home_gay.html is a service similar to AEBN, HomoActive, GayHotMovies, and GayDVD Empire.  Please create an agent for this site, similar to the other Agents in the Gay Adult Films set of agents.  Include whatever metadata the site provides (e.g., Poster, description, release date, collection tags, director, actors (with images sourced from IAFD).

Cheers!

**Comment by JPH71** [comment]
@nyethi, did you get my email that I directed at you a couple of days ago on setting cookies...
For adultdvdmarket place I also tried to set the referer to the hay site but to no avail. I am stuck like I was with GayVODClub - if you know of any agent that sets cookies could you direct me to the code so that I can look at it?

Cheers

**Comment by JPH71** [comment]
Done!
With Cody for testing!

**Comment by JPH71** [comment]
Yippeee!
