### ISSUE TITLE
[BUG]: Scenes do not match if cast list is in file name

### ISSUE THREAD

**Issue by pantherman007** [CodyBerenson/PGMA-Modernized#223]
I'm unable to get matches on scene files if the file names contain the optional [Cast List] block.  The same file matches correctly if the Cast list is removed.  Attaching two log files for the same scene - one successful (no cast list) and one failed (with cast list).

Running current Plex server on a Qnap NAS with plugins updated on 1/26/23. 
[With Cast list - com.plexapp.agents.BestExclusivePorn.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10530889/With.Cast.list.-.com.plexapp.agents.BestExclusivePorn.log)
[Without Cast List - com.plexapp.agents.BestExclusivePorn.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10530890/Without.Cast.List.-.com.plexapp.agents.BestExclusivePorn.log)

P.S. Thanks for all the work you do on these...

**Comment by JPH71** [comment]
@pantherman

This did not work as you did not format the file name correctly.

rather than:
(Fun-Size Boys) - Lounging Around Dallas Steele fucks Austin Young bareback
(2022) [Austin Young, Dallas Steele]

you should have
(Fun-Size Boys) - Lounging Around Dallas Steele fucks Austin Young bareback
(2022)* - *[Austin Young, Dallas Steele]

a hyphen between the cast list and the year.
If you look in your log file, you can see that the cast list is even
included in the search string.....

Cheers

Jason xxx

**Comment by pantherman007** [comment]
Doh!  My bad. All of my staring at the screen and missing that hyphen...   Thank you!
