### ISSUE TITLE
[BUG]: Cast/Actor Picture missing

### ISSUE THREAD

**Issue by Irfanroxx** [CodyBerenson/PGMA-Modernized#229]
# Mandatory #

## Describe the bug: ##
Sorry it is my first time using plex,so i am not sure if it my mistake or a bug.  However, I have an issue where the metadata (actor list/movie poster) is scrapped but the actor image is missing.  

## Specific Agent(s) Causing the Issue: ##
So far for all the agents i have used (GEVI, AEBN, Fagalicious)
- The log attached is GEVI

## Log Attached: ##
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11087321/com.plexapp.agents.GEVI.log)

# Optional #

## Screenshot(s) with all nudity redacted: ##
![Capture](https://user-images.githubusercontent.com/129160732/228183999-de6f9b06-d742-4f48-96e5-9def038ad469.jpeg)

## Desktop (please complete the following information): ##
 Currently using plex with synology, but I have tried using it with plex client in my desktop (windows) with the same issue

**Comment by JPH71** [comment]
Hi there

You have a mistake in your naming format -
instead of

(Raging Stallion Studios) - Guilty as Sin (2022) Scene 1

it should be

*(Raging Stallion Studios) - Guilty as Sin (2022) - Scene 1*


The format for naming files should be as follows
*(Studio;IAFD Studio) - Title (Year) - Stack No. - [Actor 1,Actor2,....]*
*Where all that is green is optional*
*A Stack - can be either Part, Disc, Scene as per plex conventions and the
Number can range from 1 to 8*

that is why in the logs you get these lines:
2023-03-28 14:02:45,745 (7f79eb654b38) :  INFO (sandbox:19) - GEVI  - UTILS
:: File Name REGEX Matched Variables:
2023-03-28 14:02:45,746 (7f79eb654b38) :  INFO (sandbox:19) - GEVI  - UTILS
:: Studio                        Raging Stallion Studios
2023-03-28 14:02:45,746 (7f79eb654b38) :  INFO (sandbox:19) - GEVI  - UTILS
:: Title                         Guilty as Sin (2022) Scene 1
2023-03-28 14:02:45,746 (7f79eb654b38) :  INFO (sandbox:19) - GEVI  - UTILS
:: Year                          None
2023-03-28 14:02:45,746 (7f79eb654b38) :  INFO (sandbox:19) - GEVI  - UTILS
:: Cast                          None
2023-03-28 14:02:45,747 (7f79eb654b38) :  INFO (sandbox:19) - GEVI  - UTILS
:: Stack                         None

Because of your convention
The year 2022 and the stack - Scene 1 can not be determined......

Jason

**Comment by Irfanroxx** [comment]
Hey, thanks for the help. That was also 1 of the problem i have been having trouble with. But my main concern now is regarding the reason the actor images are missing

**Comment by JPH71** [comment]
The actor images are retrieved from IAFD...
IAFD does not always have them, or the film can't be found on IAFD, or the
actor has a single name like James and therefore too many are returned....
if there are more than 13 or 25 matches... the scraper abandons matching...

**Comment by JPH71** [comment]
Send the title of the film and let me know what agent you used...

**Comment by Irfanroxx** [comment]
(NakedSword Originals) - Grindhouse (2013)

GEVI

**Comment by JPH71** [comment]
Hi

I guess on your system, it details that the film is not found on IAFD, am I
correct in assuming this?
On IAFD NakedSword Originals is known as Naked Sword:
You should therefore rename your file as
(NakedSword Originals;Naked Sword) - Grindhouse (2013) - This will match on
AEBN, GayEmpire and GayHotMovies
or
(Naked Sword) - Grindhouse (2013) - This will match on GEVI

[image: image.png]

I have named it as:

[image: image.png]

Cheers

Jason

**Comment by JPH71** [comment]
Amendment to my comment
(NakedSword Originals;Naked Sword) - Grindhouse (2013) - This will match on
AEBN, GayEmpire and GayHotMovies *AND GEVI too*

**Comment by JPH71** [comment]
I named it exactly as you did - And it found the film on IAFD - so ignore
my comments on renaming.....
here is how it looks
[image: image.png]

[image: image.png]

**Comment by Irfanroxx** [comment]
Ehmmmm. I have changes the titles, but the cast images are still missing. However, I think I know why it is happening, I think IAFD is a banned site in my country. So I think that is why plex is unable to scrap the cast image. 

If that is the cast, it is possible to manual add the cast images then?

**Comment by JPH71** [comment]
Unfortunately at the moment, I have not yet found a way of doing this...

Your only option to circumnavigate the IAFD ban would be to get VPN
software installed...

You can try iobit they are cheap and it works on a trial basis from what I
remember... if that works then go and install a reputable vpn...

**Comment by Irfanroxx** [comment]
Okay Thank for your help though.

**Comment by Irfanroxx** [comment]
Okay Thank for your help though.
