### ISSUE TITLE
Backing up Plex

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#23]
Hi friends,

Any best practices for backing up your Plex libraries and settings? I backup all my video files but wondering if there's another step I should do to make sure my metadata and album artwork is backed up in case of a drive failure. What do you guys do?

**Comment by CodyBerenson** [comment]
Hi @j-ktz,

Terrific question.  There's a topic on the Plex Forum specifically about backing up (and restoring) the PMS libraries *and* settings:  https://support.plex.tv/articles/201539237-backing-up-plex-media-server-data/

Since you're putting so much effort into building awesome libraries, you don't want to take any chances with losing them!

Stay safe, friend.

**Comment by j-ktz** [comment]
Perfect. Thanks Cody!!! 🖤
