### ISSUE TITLE
[BUG]: Treasure Island Media - Assgasm

### ISSUE THREAD

**Issue by dodecaphone** [CodyBerenson/PGMA-Modernized#255]
# Mandatory #

## Log Attached: Yes

# Optional #

## Screenshot(s) with all nudity redacted:

![GEVI as Main Agent for "Gay Adult"](https://github.com/CodyBerenson/PGMA-Modernized/assets/20006508/b2a97b6c-d811-4618-87bd-e683c53e158c)

![Capture](https://github.com/CodyBerenson/PGMA-Modernized/assets/20006508/83957000-fbe6-4383-954a-6296d244556a)

## Desktop (please complete the following information): ##
 - OS: [e.g. iOS] Windows 10 Pro
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] v. 114.0.5735.134

[com.plexapp.agents.GayAdult.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11776840/com.plexapp.agents.GayAdult.log)

**Comment by fourstix** [comment]
I have this movie in my collection, and GEVI agent matched this movie with a file named: (Treasure Island) - Assgasm.mp4   

I noticed in your log, that the file name contains "Sc 7".  The GEVI agent doesn't support individual scenes.  I believe the are working on a new Agent to do that.   

If you do have a stacked set of scenes, then the files need to follow a particular naming convention for them to all match up as a single movie.  (Personally, I never got to get stacked scenes to work well under Plex, so I avoid using them.  You can't omit scenes and the naming convention is very picky)

**Comment by CodyBerenson** [comment]
@dodecaphone Agree with @fourstix.  

I just tested this title using a properly named stacking convention, and it matched fine:

(Treasure Island Media) - Assgasm - Scene 7.mp4 

It appears in your log that you may have attempted a stack with "Sc." rather than "Scene" which likely interfered with the match.  

Also, in the future, please send the log that is specific to the Agent you are attempting.  In this case, please look for a log named "com.plexapp.agents.GEVI.log"

**Comment by dodecaphone** [comment]
@CodyBerenson for some reason, I thought the documentation showed Sc. as the nomenclature. 😑 thank you guys for helping! I got it to match and I'm looking forward to the GEVI plugin with stacking.
