### ISSUE TITLE
[BUG]: Cant' match my first file

### ISSUE THREAD

**Issue by Crutchfor** [CodyBerenson/PGMA-Modernized#260]
Actually I have some problems understanding the installation guide
Step 1: Clone this repository to your Plex server and copy all of the .bundle folders and 
their contents to your plugin folder.
Q1: What does "Clone this repository to your Plex server" means? Should I put all these files to somewhere else?
Q2: What does "copy all of the .bundle folders and their contents to your plugin folder" means? Should I also copy every bundle folder's "Contents" folder to the plugin folder additionally?

Step 3: Select “Exit” to safely shut down the server.
Relaunch the application as you normally would using a shortcut in your Start Menu, Dock, or the like to fire it up.
Q3: Does "Relaunch the application" means I should restart the PMS? 

Q4: As for the step 1, I just simply copied the bundle folders to the plugin folder. And at the step 3 I restarted the PMS. Eventually it failed to match the file.

Here is my folder path, E:\new\new\Wagner Vittoria\(Kristen Bjorn Video) - Sex Men (2018)
and this is my file name, (Kristen Bjorn Video) - Sex Men (2018).mp4

I used Gay Adult GEVI agent, I also tried other agents but none of them works.

It should've been matched to https://gayeroticvideoindex.com/video/60944

log here [com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11799324/com.plexapp.agents.GEVI.log)

btw I know it's stupid to ask but I want to know how can I get the token
![3M`@A1D62AZ~{5MU YCN0X4](https://github.com/CodyBerenson/PGMA-Modernized/assets/137164186/9985b203-4419-49b7-b3e2-5e51920e3931)

 - OS: Windows
 - Browser: Edge
 - Version: 1.32.4.7195

**Comment by CodyBerenson** [comment]
Hello @Crutchfor and Welcome.  It appears that most of your setup is correct.  Can you please confirm that you have set all of the preferences for the GEVI Agent.  Navigate to Settings, Agents, and click the gear for GEVI

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/e83576c6-409c-4378-bea0-ef9bc95e942c)

You will need to set each setting, even if some appear to be pre set for you.  

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/5c6dff14-e884-4ba8-80b7-a86685f04572)

Save your settings, stop PMS, and then restart.  Once your PMS restarts, try to "FixMatch" using the GEVI Agent again.  If it continues not to work, please attach the new GEVI log.  

From your log, your system was able to find your Plex Token so you don't have to worry about that.  

After we get past this first file with GEVI, in the future you will have to set all preferences for all agents you ever intend to you.

**Comment by Crutchfor** [comment]
> Hello @Crutchfor and Welcome. It appears that most of your setup is correct. Can you please confirm that you have set all of the preferences for the GEVI Agent. Navigate to Settings, Agents, and click the gear for GEVI
> 
> ![image](https://user-images.githubusercontent.com/40373801/247297863-e83576c6-409c-4378-bea0-ef9bc95e942c.png)
> 
> You will need to set each setting, even if some appear to be pre set for you.
> 
> ![image](https://user-images.githubusercontent.com/40373801/247298829-5c6dff14-e884-4ba8-80b7-a86685f04572.png)
> 
> Save your settings, stop PMS, and then restart. Once your PMS restarts, try to "FixMatch" using the GEVI Agent again. If it continues not to work, please attach the new GEVI log.
> 
> From your log, your system was able to find your Plex Token so you don't have to worry about that.
> 
> After we get past this first file with GEVI, in the future you will have to set all preferences for all agents you ever intend to you.
It didn't work for me
![RDW}4HT PBLSGWIC9D}IOBG](https://github.com/CodyBerenson/PGMA-Modernized/assets/137164186/8eec4819-2ba6-4a7b-ac9f-ef02930f6e6e)
log here
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11811318/com.plexapp.agents.GEVI.log)
[com.plexapp.agents.GayAdult.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11811329/com.plexapp.agents.GayAdult.log)

**Comment by CodyBerenson** [comment]
@jph71 can you take a look at this log please?

**Comment by JPH71** [comment]
Something has gone real wrong....
Lets go back to basics....
1. start by uninstalling Plex
2. reboot and re-install - **but don't run** Plex Media Server
3. from this repository download the whole repository
4. The files should be put under %localappdata%\\Plex Media Server\Plug-ins - assuming here that you are on Windows....
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/43102249/7a2112ea-f7b0-43cc-b16f-f743d412081a)
5. Load Plex Media Server
6. As Cody has indicated to you - go to the agents - leave as default for the time being... however, switch one setting off if its on then save, then back again and set it back to default then save.
7. Do step 6 for all the agents you want to use.
8. Create a Library and point it to a folder., select Gay Adult Films as your agent 
9. Add a film to the folder that the library points to - Make sure you have named the film correctly:
(Studio Name) - Film Title (Year) - get this from the agent you want to scrape.
10. Scan the library
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/43102249/d308fd93-ff3a-44ab-ad10-22e1df90c44c)
11. If update metadata does not start click on the lower right of the film and select refresh metadata
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/43102249/225b5f79-675a-4854-b7fc-b52c09298383)

Intitial Points to Check:
If you are using GEVI:
make sure that the film is on GEVI
Use the film Studio, film title and year as it is recorded on that
Test it works
send me the log if it fails.....

The format for naming files is strict... this saves us a lot of headaches and enables us to pinpoint when things go wrong....
You should have no extra spaces etc....

Studio names have some lee way You can use for example Next Door - rather than Next Door Ebony, Next Door Twinks etc or MEN rather than Men.com

If you want to improve matching with IAFD - the Porn Film and Cast Database - You can add the Studio name that IAFD uses if it is different, Your file name would then look like this (Studio;IAFD Studio) - Film Title (Year).

I hope this helps....

Send me your log file if nowt happens..... which I hope it doesn't! But you are a first when it comes to a whole section of the log missing!!!

**Comment by Crutchfor** [comment]
@JPH71 After a few attempts it finally worked but there are still some problems like my library section is in a mess
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/137164186/af455de3-6ff9-4af6-bbf9-80d2aa072d81)

so I made a word to show you what have I done 
[Report.docx](https://github.com/CodyBerenson/PGMA-Modernized/files/11827926/Report.docx)
and logs here (I don't know which I should upload so I just pack them up)
https://drive.google.com/file/d/1V_WLIcbaKH6NvfCq_XY30jiyiY8KBPL6/view?usp=sharing

**Comment by Crutchfor** [comment]
Besides, I deleted this library and tried again, the messy problem is till here but now I can't even load the actor photo
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/137164186/4c812192-d263-4d14-8949-4ba73977fb68)

**Comment by CodyBerenson** [comment]
Hi @Crutchfor  You have selected a large number of parameters in your Agent's settings.  This is your screen capture.  In my screen capture, none are selected.  In your screen capture, every one is selected.  For each of those selections Plex will create Collections.  What you refer to as "mess" are the collections that Plex created because of the selections for your settings.  If you don't want one or more of the Collections that were created, you should uncheck it/them in your settings, save, Stop PMS, and then Restart it.

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/be9b9d3c-7a13-4d5d-a368-e023d8406363)

**Comment by CodyBerenson** [comment]
@Crutchfor:  Regarding the actor photos, IAFD has introduced new cloud protections that is limiting the ability of the Agents to scan and retrieve metadata and images.  Jason, the PGMA developer, is currently addressing.

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/07de693b-a60c-4d80-ad7b-8d351d6b1221)

**Comment by JPH71** [comment]
Now that you have got it to work.
Go back into the preferences.
Turn off collections you don't want to use
Save the preferences
Go back to the library and delete all the collections
Move all the film titles out of their folder that the library points to.
Re scan the library
Restart Plex Media Server
Put the films back into their folder
Plex should pick them up and re scrape them...

The reason for moving the films out if their folder is to remove locks on
the metadata fields.

If you delete a collection Plex locks that field and thus it can't be
updated.

Jason xxx
