### ISSUE TITLE
GEVI Updated their site which broke the Films and new Scenes Agent

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#261]
Jason is aware and looking into the issue.

**Comment by JPH71** [comment]
Gevi should be ready tonight... if I don't have too much vodka..

**Comment by CodyBerenson** [comment]
You’re describing every night for me since the pandemic. I got a vodka
infusion recipe book for Christmas . 24 pieces of the same flavor of jolly
ranchers candy (eg sour apple) in a pint mason jar. Fill the mason jar with
vodka. In a week put the glorious concoction in the freezer. Yummmmm

**Comment by JPH71** [comment]
Ooooh daddy...

**Comment by CodyBerenson** [comment]
Hi folks.  Jason fixed the new GEVIScenes to work with today's GEVI site changes.

**Comment by j-ktz** [comment]
Where in the file name do we put the GEVI scene number? I looked in the usage guide and didn’t see and saw Cody’s screenshot but didn’t see a screen number.

**Comment by JPH71** [comment]
You name them like this:

(Raw Fuck Club) - Bruno George 2.0 - {182816N} (2023)

182816 - been the episode number from the url Bruno George 2.0: Gay Erotic
Video Index <https://gayeroticvideoindex.com/episode/182816>
This episode number has to be followed by an *L* (Rotate Left) or an *R*
(Rotate Right) or an *N* (No Rotation) - This because the pictures are
usually portrait and Plec does not always get it right when it tries to fit
it into the poster format 2:3

The episode and rotation have to be enclosed in curly brackets *{}* and be
separated from the title with a *Space-Dash-Space*

All other naming rules in regards to cast apply....

Jason xxx

**Comment by CodyBerenson** [comment]
> Where in the file name do we put the GEVI scene number? I looked in the usage guide and didn’t see and saw Cody’s screenshot but didn’t see a scene number.

@j-ktz there's always one......oi.....The instructions for using this new agent can be found beginning on page 26 of the updated usage guide.

**Comment by CodyBerenson** [comment]
GEVI Update for all:  https://github.com/CodyBerenson/PGMA-Modernized/discussions/262#discussioncomment-6379515

**Comment by CodyBerenson** [comment]
Hi folks, Jason has coded a fix for GEVI. I didn't have a lot if time to test. I tested with ten titles, current and dated, All ten matched and scraped. Please open a new issue if you run into any failures.

**Comment by JPH71** [comment]
Thanks Cody...
I had some 184 proof Slovak tatra tea... I am in bliss land at the moment... and full of smiles...
