### ISSUE TITLE
Default regex for filenames

### ISSUE THREAD

**Issue by MrPlow254** [CodyBerenson/PGMA-Modernized#31]
Id suggest switching default regex from:
`^\((?P<studio>.+)\) - (?P<title>.+) \((?P<year>\d{4})\)`
to:
`^\((?P<studio>.+)\) *- *(?P<title>.+) \((?P<year>\d{4})\)`

it would allow for `"(Active Duty)      -      Phoenix River and Ryan Jordan           (2018).mp4"` to still be found in case there is a space typo. GitHub removes spaces so you cant see the example

also trim the whitespaces before and after the variables in the matchFilename functions of the __init__.py files

**Comment by JPH71** [comment]
@Nick Smith... I agree with you that it would allow for space typos, but
having it this way forces consistency in naming..
However, I left the regex as a preference so that users can change it and
use different types of brackets etc
But it's good to know there is another scripter in the ranks..
If you have ever done any web scraping do let me know @jph71
👍👍

**Comment by CodyBerenson** [comment]
@MrPlow254 

Thanks so much for adding the link!  I had thought about asking if you'd grant a pull request that added our repository's code to yours, but instead do really appreciate the link!

**Comment by MrPlow254** [comment]
I need to look over your code more. Some of what I've seen has headed into a different direction than I planned. It would be nice to merge the code into one repository. But i also don't have enough time to program this which is why mine is inactive.

For this issue #31 at minimum a trim before and after should be performed in the function to broaden regex queries that can be performed without breaking the code. I had all my videos in studio name folders for better maintenance for me. With only the video name within the folder.  I have different raid drives that are almost at max capacity and moved folders around on different raids. I added prefixing to all my videos of a different format than default which needs trimming before and after.

**Comment by CodyBerenson** [comment]
No worries, the link is fine and appreciated.

Given that nearly every indexing site uses a different name for any given studio...and often multiple studios have a similarly named movie...a rigorous standardized naming convention works well...especially for folks that may look at a regex and see greek.  :)

**Comment by JPH71** [comment]
As it stands now for example.. if you have a film titled (falcon) - film
(year)... It would match to (falcon studios) - film (year) or to (falcon
international)....
 Etc

Studio matching also involves whitespace removal... So Kristen Bjorn
matches KristenBjorn

I used to keep my films in studio folders.. but there are loads of
studios.. and if by mistake you move one film to another folder.. the only
way to identify it is to open the file...

It's better to include the studio name and year as a minimum when
cataloguing films...

There are some good renaming utilities to insert a prefix on all files
within a folder...

**Comment by MrPlow254** [comment]
Like what? Radarr? I created a batch file to add prefixes. If you are saying there is something that does it better than a command line i'd like to know.

**Comment by MrPlow254** [comment]
You could also add the option to use folder naming for studios or file naming. Just have a checkbox to enable/disable it.

**Comment by CodyBerenson** [comment]
@jph71 LOL as your partner in crime, I didn't know about falcon vs falcon studios vs falcon international and whitespace in the studio name.  Thanks for holding back.  LOL!    Skeptically, I just tested it all out, and it works great.  More flexible than I had thought....so perhaps I'll update the FAQ.  

I've always liked the idea of using the name of the folder for the studio...that functionality never worked for me on the old AEBN Agent and i'd always just get the first match when a common title is shared among multiple studios....I'll defer to you if you want to provide additional flexibility...its definitely a pro.....although as a con, I do get what you're saying about moving files by mistake (in my case, typically vodka induced).  

re: renaming, personally I use Bulk Rename Utility.  I quite like it.  Especially when I want to bulk create a subfolder named individually for each file in a directory, and move each file to the new subfolder (which i do for scenes that aren't blogged on WB, QC, or F and only match on IAFD because i want to have drop a poster in each folder instead of uploading thru Plex). 

https://www.bulkrenameutility.co.uk/

**Comment by MrPlow254** [comment]
The advantage of using folders is you can have a torrent complete and be moved to the folder automatically when the torrent name matches the studio name - not saying i do that lol. It isn't always known when the year is either. That part should be optional but it is known that results might not be found if it isn't used. I'm all about automation, and simplistic.

Thanks for that app. Pretty handy!

**Comment by JPH71** [comment]
@codyberenson
Sorry... I really did think I had mentioned it before... As the blog sites
sometimes remove the whitespace...

I also put my movies in studio folders especially if the studio is very
active and you have loads of their movies..

But the reason I took to using the studio and year was the same issue you
got with the old aebn of just picking the first title it matched if it
found one at all..

I tend to use IAFD or GEVI to find the years... When I don't know the year
I set it to 1900 then run the scrappers against it and check the log files
because if it finds a matching title it logs the website.. and checks the
date if any. It's then quite simple to change the year of the file title
and re-scrape... If it doesn't find the title.... U get my flow...

One thing I want to do with the studio matching is to get it to ignore
.com, .net, .org suffixes especially in the blog sites so that one can use
Kristen Bjorn instead of KristenBjorn.com

In my view if we get rid of the studio..film..year we weaken the integrity
of the scraper and we are back to the mismatching of the old style AEBN...
It's preferable to have a non match to a wrong match...

In only one case have I come across a mismatch where one studio had 2 films
of the same name in the same year... Hot house - hole busters 2010... One
was part of a series... This was when I was asking what you thought about
series number 1 at the end of the film title... If we insist on it or make
it optional...

**Comment by JPH71** [comment]
However even if you torrented it to the lib folder ... You would still need
to clean up the torrent file name as they are notorious for adding codecs
and all sort of stuff and may not even have the title of the film in the
video file..
So if after torrenting you have to rename the file or the folder it resides
in.... Wouldn't it just be the same as renaming the file as the scrapper
insists?

**Comment by MrPlow254** [comment]
That’s why you use the scoring system in Plex. I wasn’t renaming my files it just searches different parts of the names and strips known naming conventions. If it found a poor match it was rejected until it found a positive match. But I was also searching directly on the studios sites. These other sites I had loads of issues with and was going to make my own api site but someone I was working with lost their funding. But back to what I’m saying. You have to google the video to find the year it was made. Torrents don’t include that or rarely do.

Keep it simple for the video name. Have the program do all the hard work

On Jun 20, 2020, at 9:54 PM, JPH71 <notifications@github.com<mailto:notifications@github.com>> wrote:


However even if you torrented it to the lib folder ... You would still need
to clean up the torrent file name as they are notorious for adding codecs
and all sort of stuff and may not even have the title of the film in the
video file..
So if after torrenting you have to rename the file or the folder it resides
in.... Wouldn't it just be the same as renaming the file as the scrapper
insists?

**Comment by JPH71** [comment]
The scraper searches through lists of titles returned by the search...

When it finds a match it compares against the studio then year, if all
match it gets a score of 100, and it's metadata gets updated...

The problem with scoring is that you have to determine the score, then from
that match...

There is this a chance of mismatch..

It just makes logical sense that it either matches or doesn't.

After all that's the whole reason why one is running the scrapper..

**Comment by MrPlow254** [comment]
How about instead of comparing the year someone types in manually pull the duration of the video file and compare that to the duration on the site. I don’t know if all sites publish the video duration but those that do this will offer another scoring boost. It would be file duration +/- 5%.

I’m also not disagreeing with what you are saying, but your code is too strict it doesn’t make it simple. Even the default Plex tv and movie scraper messes up from time to time I just have to hit be fix match on the title(s). You aren’t even giving Plex that option. 

Takes longer to set up a file name correctly if you don’t know a year, which is every file. Let Plex do the hard work... give people a list of mismatched titles to pick from that are the same title as the file name or has a 86%+ match. Only give a file a 100 if you have all the optional information collected and matches.

As of now if the title fails; when people are browsing for a video they see a bunch of "studio name" "title" instead of just the title. Bare minimum you should be stripping the studio name from the title of the video and assigning it to that studio and rank it 86 since you are looking for a specific format.

**Comment by JPH71** [comment]
Most sites do publish the duration but unfortunately as the videos have
being converted by different people.. many videos won't have opening and
closing credits... Sometimes missing scenes or bonus scenes added.. so
using duration is not useful...

**Comment by JPH71** [comment]
In relation to this 86% what happens when one does a refresh metadata...
How does Plex update? Does it pick the one with the highest score?

I know when you fix match it can be scripted to give one a series of movies
to match against... But even then you would need to know the studio and
release year of the film to choose the correct match... So why not name it
correctly in the first place?

In my view it does not help... This view of course is helped by my not
understanding how Plex handles scoring... Or how is the update triggered if
the score is low...

A bad match is far worse than no match at all....

**Comment by MrPlow254** [comment]
Yes, anything higher than 85 is matched. The highest score is selected by default. Here is an outdated manual for plex i snagged a few years back.
[plex.pdf](https://github.com/CodyBerenson/PGMA-Modernized/files/4809354/plex.pdf)

It is different when you are sharing names between studios. When i was getting it directly from the studio itself there were a lot of false negatives. You will be getting a lot of false positives where the scoring system will come in place.

**Comment by JPH71** [comment]
I will think about it... It will most likely be a system where there are
three levels of matching..
1. Strict .. studio-title-year
2. Medium.. title-year
3. Loose.. title

But I really do not like the idea that mismatching will definitely occur,
just because a user can not be arsed to name a file correctly...

What happens if after a low match ... Does Plex ever try to rematch if for
example I add another site which matches better?

It would be nice to be able to get Plex to behave differently when one
asked to refresh metadata as opposed to fixing a match... Then one could
use strict, medium or loose to get possible titles when fixing the match
and additionally use the selected information to rename the file on
selection...

**Comment by MrPlow254** [comment]
By default, your server will automatically clean up old bundles once a week as part of Scheduled Tasks. You are also able to refresh all metadata for a folder or selected videos in addition to the entire library.

Fixing is only used when there are two titles for example the flash tv series has the same name of two shows. One was started in 1990 the other in 2014. If the year is not in the filename or the file title property it will default to the 1990 version, but gives the option to fix the match, which lists both.

Plex will hold onto the match until the agent tell it to stop. Once it receives a stop signal it will use the match if it exceeds the 85 points. You will need to add linking between agents. Which looks like you have by doing the contributes_to. That is all that is required to have it search all the agents before setting the highest result as a match.

**Comment by JPH71** [comment]
Is there a variable that one can access the match score within the update
routine... This so one can set the studio, title and year if one opts for
strict matching?

**Comment by MrPlow254** [comment]
I don't know, but i don't think so. Once matched it is for the specific url the metadata is pulled from. The score shouldn't ever change. If you change an agent preference i'd assume you'd need to refresh all metadata again. This is where it sucks that plex removed there dev help document.

**Comment by MrPlow254** [comment]
I guess to clarify. You'd have to check for all the options and rank the score in the search function and not the update function

**Comment by JPH71** [comment]
It's a shame one can't access the score from the update function..

I think I will leave it as it is, it seems not worth the effort if it is
not going to enhance matching...

When one is downloading porn.. in my example I always use the studio and
film title to find movies...I then append 1900 as a date and scrape.. if
one checks the log files after an attempted match one can see if the
scrapper has found a date and amend the file name to reflect this... Then
it matches correctly next time round...

When a user sees a matched movie he knows he has it correctly matched...

**Comment by MrPlow254** [comment]
You do get the functions confused. The matching is done in the search function not the update function. All new videos or videos that you refresh the metadata on will run the search function then the update function.

You obviously are dead set on not changing the code. I am just suggesting how to improve it to enhancing the matching. Your code is way too strict and are also getting 100% false negatives. You need to open it up to have false positives and use the scoring system to get the highest ranked match. All that is needed is the title name and the rest improve the match criteria. The agent needs to be versatile in the file name. Way too much effort is being made in making sure the filename is correct instead of making sure the agent can find the correct match. It is ass backwards.

**Comment by CodyBerenson** [comment]
@MrPlow254 

We really do appreciate your feedback and suggestions.  It is an intriguing suggestion to open up the rigid consistency that we've built into the naming convention and consider utilizing Plex's native ranking.  You have our word your suggestions have not been summarily dismissed and will be considered.  We have made plenty of enhancements based on feedback:  e.g., inline poster image cropping, foreign language translation of summaries, and handling special characters that the various indexing sites use.  It could well be worth a proof of concept and pilot.  

The Agents here work really, really well.  The feedback that we've received thus far isn't from a community of programmers who get the intricacies of python or how plex does what it does;  rather, we hear loudly when exact matches are not able to be made...those rare instances of false negatives.  Speaking from experience with the legacy AEBN agent, I'm not sure introducing an opportunity of a mismatched file is an improvement.  That's not me pushing back on you and your expertise.  That is me having spent countless hours building libraries using the legacy Agent and the newer agents on this repository.  I therefore consider myself a bit of a match/fixmatch/unmatch/slam-the-mouse-on-the-keyboard-when-it-doesnt-match expert and am intrigued by your suggestions...in the end it will come down to a balance between accuracy and efficiency....and if there's a way to soundly achieve both we should pursue.  

Finally, if you do feel that you're not being heard, as you know (better than I), the terrific thing about GitHub is that you are able to branch code, make updates that you believe to be helpful, utilize to your heart's content and if you'd like, suggest a pull request.  It would be really appreciated...and welcomed.

Thanks again, both for pioneering/hosting the early agents back in the day, and offering meaningful, expertise-based feedback to our revitalized collection.

Cheers,

Dakota

**Comment by MrPlow254** [comment]
I will be updating my code in a few weeks. You guys can use it as research on the scoring system. Hope i didn't come off harsh on my last comment. I will also be renaming the agent so people can install both of ours without conflicting each other. I'm staying away from aggregated video sites and will be sticking with studio direct for now, no sense in reinventing the wheel. This is the major difference between the two agents. Really there needs to be an API site which gayporncollector.com was going to be it but the host lost the site and went MIA. Hope he didn't go to jail over it lol.

**Comment by JPH71** [comment]
You did come across as harsh. I suggested. A three tier level of matching
strict,medium and loose which you didn't acknowledge... As Cody says you
should be able to fork off the main repository and develop a legacy style
system...
