### ISSUE TITLE
HELP... i'm not a programmer and am new to PLEX 

### ISSUE THREAD

**Issue by xgymnast** [CodyBerenson/PGMA-Modernized#317]
With plex no longer supporting plugins.... without going back to the versions that they did.... how do i install and/or use your repository? I downloaded and installed webtools and it runs on my windows pc. But i have like 600GB of porn i want to sort thru with your "pgma-modernized".... 

i'm starting to feel really stupid.
please help

jason

**Comment by JPH71** [comment]
Follow the instructions in the document Cody authored paying attention to
the format,
(Studio) - Film (Year)
And you will be fine.

**Comment by CodyBerenson** [comment]
@xgymnast our Agents don't use webtools.  Please close the issue.

**Comment by xgymnast** [comment]
I haven't even gotten to the point where it is ready to scan the files. I
don't understand how to install it in "webtools ng" or am I supposed to try
and use old webtools??

Jason

**Comment by JPH71** [comment]
Download the zip and place it in the plugins folder

Then restart plex media server

The agents should then appear...

Cody has written an installation document that explains all of this...
Pgma is not in the webtools system...

Let me and Cody know if you have any issues xxx

**Comment by ms52538** [comment]
Not sure what source of information you are attempting to use in order to
facilitate PGMA in your Plex System, but the PlexTools library has ZERO
affiliation with PGMA. I suggest you download the agents from the site
here, unzip, go to the IMAGE folder within _PGMA and read the PDF
instructions, which is what you should be doing. Then, go from there if you
have questions. If you are already in doing that, please cite the page
number of the guide you are referring to.  Good luck!
