### ISSUE TITLE
Match issue with Dr. Jerkoff & Mr. Hard

### ISSUE THREAD

**Issue by mhunter8** [CodyBerenson/PGMA-Modernized#46]
Hey Guys... I've tried different combinations with this to no avail.

I have the title as:  (Big Video) - Dr. Jerkoff & Mr. Hard (1996)

The problem seems to be the &, which is removed.  
The search query generated:
https://www.gayeroticvideoindex.com/search.php?type=t&where=b&query=dr+jerkoff+mr+hard&Search=Search&page=1

finds nothing.  But if you modify it and add back in the & and use:
https://www.gayeroticvideoindex.com/search.php?type=t&where=b&query=dr+jerkoff+&+mr+hard&Search=Search&page=1

It works.  

Any ideas on how I can work around this?  Thanks much!

**Comment by JPH71** [comment]
Hi MHunter8

I will make the change to GEVI to sort this out ....
The search string is supposed to return everything before the "&" and
search on Dr Jekyll... when you click on your amended link you will see it
returns everything before the ampersand...
As it stands its replacing the ampersand with a space incorrectly and not
finding owt as GEVI searches for the whole string rather than words in the
string like gay hot movies...

Regards

Jason

**Comment by JPH71** [comment]
Hi Mhunter8

Corrections made to GEVI,
Code with Cody for testing.

Thanks for finding this error...

Cheers

Jason

**Comment by CodyBerenson** [comment]
The update fixes this issue.  Typically, I'd do a lot more robust testing on updates to make sure nothing broke but I just don't have the time so I'll upload the corrected Agent to the master repository in about 3 minutes.

**Comment by CodyBerenson** [comment]
@mhunter8 you should be good to to.  Stay well.

**Comment by mhunter8** [comment]
Great... just tested... works perfect.  Thanks again for your quick assistance!  Much appreciated!

**Comment by JPH71** [comment]
you are always welcome!
