### ISSUE TITLE
Cannot get this to match :(

### ISSUE THREAD

**Issue by joshallen13** [CodyBerenson/PGMA-Modernized#49]
I've tried every possible combination I can think of, including dashes, capitalization, omission of the "the video" part and inclusion of the year (found on AEBN). Would appreciate if you could help me out.

https://www.gayeroticvideoindex.com/V/9/18739.html

Also, this one seems to be the same. I've had troubles getting anything with a secondary title to match it seems since the most recent big update.. (2 updates ago?).

https://www.gayeroticvideoindex.com/V/7/49807.html

**Comment by CodyBerenson** [comment]
Hello @joshallen13 

Hope this finds you well!  :)

The easiest part first:  the second example you give matches fine, if you make sure to use the properly named file:  
(Raw Joxxx) - Balls to the Wall, Dylan Saunders in (2013).mp4 

This precise example is covered in the readme for GEVI.  This example aside, you mentioned you are having troubles with other similiar titles, do be sure to give me examples for them...perhaps we've introduced a bug, just not in this precise example.  

Now, the more complicated one:  I get the same result, won't match.  Jason loves to be challenged so he will need to take a look at it.  He's on holiday at the moment, so it may take a moment or two for him to see.  

@jph71:  please take a look at this file.  because of the common name to it, the search results return many, many titles and perhaps it craps out after a certain #?  

https://www.gayeroticvideoindex.com/V/9/18739.html

Cheers!

Cody

**Comment by joshallen13** [comment]
As for the Raw Joxxx, I had exactly that, and it won't match for me. See the photo
![Screen Shot 2020-09-27 at 8 39 58 PM](https://user-images.githubusercontent.com/33143443/94379998-b2b91080-0101-11eb-96a2-78f798ef0b6b.png)

The second, is a little tricky cuz of the studio crossover I believe between McKey Productions, Hot Desert Knights, & Dick Wadd. I tried all those studios/companies as well.

**Comment by CodyBerenson** [comment]
@joshallen13 

re: rawjoxxx please stop your PMS, restart it, do a fix match and please attach the gevi log. also, please let us know what OS your PMS is on. it matched perfectly for me on the first try so we will need to see your log and investigate further. 

re: the hot desert knights title you’re overthinking. each agent strictly goes by the metadata on the particular site. gevi has no reference to dickwadd or mckey productions, and would never match using those. another site may list dickwadd as the studio so it would be appropriate to use it to match with that site‘s agent.  

nor do the agents care about capitalization (or not) when matching (the exception is our new scene agent that uses capitalization to infer actor names). also, if year is missing (as in this case) the agent doesnt care what value you use for (YYYY) as long as you include it in the name of the file. since its mandatory, youll never get a match if it is omitted.

**Comment by JPH71** [comment]
Hello @joshallen13 <https://github.com/joshallen13>

Sorry for the delay.

I have tested the following names:

*(Hot Desert Knights Productions) - Bareback 1 - The Video (1998) - *I got
the date of AEBN, but it would work if he put any valid YYYY date here -
This aso works if you prefers the AEBN naming style which drops the first
in a series i.e *(Hot Desert Knights Productions) - Bareback - The Video
(1998) *

*(Raw JOXXX) - Balls to the Wall, *Dylan Saunders in* (2013)* - worked
without issue too.
Maybe your issue is that you are using an em-dash rather than a standard
hyphen.... look at the log file and see why it's whingeing.

There should be a new GEVI coming out soon as I had to make some changes on
round-about dates but this should not have affected the matching of these
two titles.
As soon as Cody runs a few titles against it - it will be uploaded.

Kind Regards and thanks for using the agents

Jason

**Comment by CodyBerenson** [comment]
@jph71 

Your fix addresses the issue and the HDK title now matches as expected.  

@joshallen13 

I've uploaded the updated agent to the master repository.  I'll close this issue as resolved tomorrow.

Cheers, all, and stay safe.

**Comment by joshallen13** [comment]
Sorry I did not get to you this week. It's been a little crazy.

Among the crazy I lost my server settings and backup so I had to completely set up a new server and it seems to be a little iffy but slowly matching titles. Soooooo lots of fun! :D

**Comment by CodyBerenson** [comment]
@joshallen13 

No apologies!  Really sorry to hear that.  That's one of my fears for sure.  :(

Not that it will help, but among the future enhancements that @JPH71 has planned is an enhancement to create individual xml files for every title in your library....for just such a tragedy (or for folks that want to move libraries and the built in plex stuff to do that doesn't work).  that way, no lengthy churn as the server makes calls back and forth across the internet to the indexing sites.  Rather, just quickly locally rebuild the metadata from the xml data for each title.  the xml files take only a small footprint.  Again, sorry, i know this doesn't do you any good now...but perhaps in the future.

Take care.  :(

**Comment by JPH71** [comment]
Ouch... That's a right pain
I am also rebuilding my plex server at the moment as I just built a new
PC....
Hopefully all should be matched overnight,,,

**Comment by joshallen13** [comment]
It's not matching automatically for me after the rebuild. I'm having to go to each entry and select "fix match", choose Auto Match and then 'Gay Adult' in the dropdown. Then it will think for a while before matching. It will also only do 3 spinning circles on the titles at a time, but you can select more than that. Does that sound right?

**Comment by CodyBerenson** [comment]
I find Plex to be rather persnickity.  Everything you're describing is unfortunately how standard Plex functionality works and my experience when rebuilding libraries (porn or otherwise).  I believe Plex's reasoning for only churning on 3 matches at a time is because 1) it doesn't want to crash your processor because of too much multi-threading, and 2) it doesn't want the requests to the indexing sites, porn or otherwise, to misinterpret the calls as a denial of service attack and blacklist you from hitting the indexing site.

The churn will take less time if you limit the agents that you've selected to *only* those you use regularly. For a long time, I was under a misconception about how Plex's standard functionality works.  Let's say you have 8 agents selected.  Plex uses the order of priority for Agents STRICTLY on where to grab metadata from, should it find a match.  It will still churn through internet calls to all 8 agents, per title, even if its able to successfully match against the 1st agent.  I assumed, quite incorrectly, that once it found a match, it stopped trying to match the title against the rest of the agents.  Hence my suggestion to limit your agents to those few that you really use regularly.
