### ISSUE TITLE
GEVI has updated their site which has broken our Agent from pulling in poster artwork

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#57]
Happy New Year Folks!  Jason is working on a fix.  Stand by.  

p.s. Jason is also close on a fix to Fagalicious.

**Comment by j-ktz** [comment]
A 2021 miracle. ✨ Stay safe boys!!! Let me know if you need me to test
on a Mac. 

On January 8, 2021, GitHub <notifications@github.com> wrote:
> Happy New Year Folks! Jason is working on a fix. Stand by.
>
> p.s. Jason is also close on a fix to Fagalicious.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CodyBerenson/PGMA-Modernized/issues/57>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AOEY5RHP62H6FEN3NQXUO2DSY6KM5ANCNFSM4V3DN2PA>.

**Comment by JPH71** [comment]
Hey J-ktz

Hope all is well with you! Happy New Year!

**Comment by CodyBerenson** [comment]
The fix has been uploaded to the repository. We will leave this issue open for a day or so to see if anyone in the has feedback. feedback.

**Comment by j-ktz** [comment]
@JPH71 @CodyBerenson Dream team! I'll download and do some testing. Got lots of new videos to match. 😉

**Comment by CodyBerenson** [comment]
@j-ktz Thanks Cutie.  Jason made a slight tweak.  Please download the newest version that I just pushed to the repository.

xoxo
