### ISSUE TITLE
Matching issue

### ISSUE THREAD

**Issue by mscrawford5** [CodyBerenson/PGMA-Modernized#58]
Ive added your plugins to my plex/plugin folder and have setup the agents in my settings.  However I am unable to match any titles at all. I've tried formatting titles in every way possible and read through your installation guide numerous times and still have no luck.  I'd like to match my scenes based off waybigblog or queerclick but cant seem to match a single scene.  Any clues what I could be doing wrong? I can include logs if that helps? which ones should i include? 

Thank you in advance

**Comment by j-ktz** [comment]
Logs and screenshots would help!

On January 30, 2021, GitHub <notifications@github.com> wrote:
> Ive added your plugins to my plex/plugin folder and have setup the
> agents in my settings. However I am unable to match any titles at all.

> I've tried formatting titles in every way possible and read through
> your installation guide numerous times and still have no luck. I'd
> like to match my scenes based off waybigblog or queerclick but cant
> seem to match a single scene. Any clues what I could be doing wrong? I

> can include logs if that helps? which ones should i include?
>
> Thank you in advance
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CodyBerenson/PGMA-Modernized/issues/58>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AOEY5RGMU5WO54IA7RNGYDTS4NOPLANCNFSM4WZZUM3A>.

**Comment by mscrawford5** [comment]
[Plex Media Server Logs_2021-01-29_20-29-53.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/5897131/Plex.Media.Server.Logs_2021-01-29_20-29-53.zip)

<img width="542" alt="Screenshot 2021-01-29 203528" src="https://user-images.githubusercontent.com/77306933/106343072-9a086500-6271-11eb-9100-5be74bc6a191.png">

Attached are the logs and an image of what I get every time I try to do a fix match .

**Comment by j-ktz** [comment]
We need the plugin logs, not the regular logs. Here's a guide on how to

find them: https://support.plex.tv/articles/201106148-channel-log-files/


If you're trying to match Waybig or Queerclick, make sure to include
those. 

On January 29, 2021, GitHub <notifications@github.com> wrote:
> Plex Media Server Logs_2021-01-29_20-29-53.zip
> <https://github.com/CodyBerenson/PGMA-
> Modernized/files/5897131/Plex.Media.Server.Logs_2021-01-29_20-29-
> 53.zip>
>
>
>

> Attached are the logs and an image of what I get every time I try to

> do a fix match .
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/CodyBerenson/PGMA-Modernized/issues/58#issuecomment-

770132784>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5RCDFT42RSCTX7LY76TS4NPC7ANCNFSM4WZZUM3A>.

**Comment by joshallen13** [comment]
While certainly not my place to make any assumptions on the validity of this issue causation, I was noticing part of the file information has parentheses enclosing the section of the file names that should be open between the studio and the release date. See the photo attached. I would advise trying the match without the parentheses as indicated in the photo grab here. 

Hope that helps your tagging woes!
![Uploading Screen Shot 2021-01-30 at 12.13.25 AM.jpg…]()

**Comment by mscrawford5** [comment]
I appreciate all the help.  New to a lot of things with Plex.  I've tried with the parentheses and without. All with the same results.  I've
 attached a zip version of the logs.
Thanks again
[PMS Plugin Logs.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/5897447/PMS.Plugin.Logs.zip)

**Comment by mscrawford5** [comment]
I finally got it work. Thank you for all your help and hard work :)

**Comment by j-ktz** [comment]
Awesome! Happy to hear. Enjoy. :)

On January 30, 2021, GitHub <notifications@github.com> wrote:
> I finally got it work. Thank you for all your help and hard work :)
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/CodyBerenson/PGMA-Modernized/issues/58#issuecomment-

770165587>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5RBSQVYH7J72HRUGKK3S4OQFPANCNFSM4WZZUM3A>.

**Comment by CodyBerenson** [comment]
Good morning everyone.  What a great community!  Happy New Year to all y'all!

@mscrawford5 Welcome to our agents.   I'm really happy you were able to figure out the match.  

Just to completely clarify, in your example above, here is the proper title on WayBig:

![image](https://user-images.githubusercontent.com/40373801/106359025-b8a44580-62dd-11eb-8e1c-6cf383a336aa.png)

With WayBig, no need to change/add/remove parantheses, quotes, punctuation of any kind, etc. to the title AS-IS on the website.  In fact, do not, or it will not match.  

Therefore, the filename should be named exactly:

(ActiveDuty) - Quentin Gainz & Jeremy Diesel (Bareback Flip-Fuck) (2015).mp4

With the agents, (other than specific quirks with specific sites called out in the instruction guide), change NOTHING other than 

1. putting the studio with parentheses (in this case Active Duty),
2. changing the ":" to a " - " (i.e. replacing the colon with a space dash space) and 
3. adding the year at the end within parentheses (2015).  

Once you get into the above 1, 2, 3 battle rhythm,  things will match easily for you, 1st time thru.

I'm going to leave this open for just a bit, as it is a typical 1st time user challenge.  Feel free to continue to post any challenges you run into or questions you have.

Cheers

Dakota
