### ISSUE TITLE
AEBN has updated their site and broken Poster Fetching 

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#61]
@JPH71:

AEBN has made an update to their site which has broken our agent's ability to fetch poster art.

**Comment by JPH71** [comment]
I will look at it next!

**Comment by CodyBerenson** [comment]
Turns out GEVI's update a little bit ago broke the agent from returning higher quality posters as well.

**Comment by JPH71** [comment]
They have completely hid the links to the high quality photos... the mouse
over image you see I think is javascript......

**Comment by joshallen13** [comment]
Doesn't pertain to AEBN, but is related so this is where I wanted to put this as a suggestion for my interpretation of this issue.
Keep in mind, I'm new to python and how this all works, but my understanding of Front-End HTML and Javascript lands me here to share what I think is a fix for GEVI.

This was in the news feed from the GEVI main page I saw recently because I noticed the poor quality as well. So, I started to switch to AEBN to temporarily pull the high quality art in and then rematch back to GEVI for descriptions and stuff for continuity, but now they've broken their ability to as well.  So, in the spirit of me trying to learn how to code and what not, I looked into the code and the web inspector to see what info was available from the search. 
```
>
1/14/2021
--
Recent Changes Causing Problems?
We recently put in a few changes that should have been minor but are causing problems. 
The DVD covers were changed from click-to-expand to hover-to-expand like the VOD episode pictures are. 
That way all pictures expand the same way. If you are having problems with that or other behaviors, 
try doing a force reload and/or clear cache. 
An old page may be looking for page behavior instructions in the wrong place. 
Still having problems drop a note to woody at wtule dot net noting your browser and OS. 
Sorry about that. Apparently we aren't as clever as we thought.
```
So, in the spirit of me trying to learn how to code and what not, I looked into the code and the web inspector to see what info was available from the search. I think the javascripting is just to save on bandwidth resources and not attempting to mask the source file for the larger image.

@JPH71, because the javascript is hover to expand now and that no longer requires the click, the high quality photo is still referenced somewhere. I looked at the Web Inspector and was able to easily find the larger quality was available in the Source list just under a slightly different path. Is there a way to adjust the GEVI agent to NOT pull the image based on the path listed with the variable "Covers", but instead to exclude the variable "Icons" so that the correct path for the image source is located? 

Example: 
[3 is Never a Crowd](https://www.gayeroticvideoindex.com/V/4/66594.html)

Here, the film has the images as "Icons" based on the path URL and source of:
```
https://www.gayeroticvideoindex.com/images/Covers/Icons/4/video66594.jpg
Scheme	https
Host	www.gayeroticvideoindex.com
Path	/images/Covers/Icons/4/video66594.jpg
Filename	video66594.jpg

```
The larger file that I located is in the sources list as well at the following location:
```
https://www.gayeroticvideoindex.com/images/Covers/4/video66594.jpg
Scheme	https
Host	www.gayeroticvideoindex.com
Path	/images/Covers/4/video66594.jpg
Filename	video66594.jpg
```

Please correct me if I'm wrong, but I am learning and thought this could be a viable solution.  I also looked at this agent code from the last update and not the one from roughly ~ 10 hours ago now. So, I could be way too late to the party and referencing something already looked at and adjusted.

Hope this helps. Thank you boys for the massive sanity you've brought my obsessive compulsive disorder and media viewing habits. :)

**Comment by CodyBerenson** [comment]
Thanks @joshallen13 !  Hope you are doing well....

Kudos!  I believe you're deduction is spot-on correct.  Jason identified the same root cause last night and we pushed the fixes to both AEBN and GEVI late last night.  

You rock!

**Comment by joshallen13** [comment]
OMG I might print that out and hang it on the fridge like my mom used to do back in elementary school. 
I am pushing the update now as I hadn't yet done so when I was doing the research to support my theory. I was really hoping that I had found something that you guys might have missed, but y'all are on top of it!

You guys rock for keeping so on top of the agents breaking randomly!

**Comment by CodyBerenson** [comment]
@joshallen13 

I'm probably not telling you something you don't already know....but that's the magic of github.  you can create your own branch, tweak/learn/experiment to your hearts content, your previous versions are there in case you muck something up and need to revert, and offer back improvements you may come up with!  That's how Jason and I met.  There was a little-maintained site of agents...Jason re-engineered them ground up...I'd then test, document, and version control them....and the rest is naughty history.  Jason would likely really appreciate the coding camaraderie you offer.  I'm clearly not the coder...I'm just the pretty-face of the operation.  LOL!

When you do find an issue, don't hesitate to raise it (and figure out the solution, if you'd like).  Neither Jason nor I noticed the lower-quality GEVI coverart until our new friend joined and mentioned it.   Jason thrives on being challenged and finding the solution.  

Stay safe!

**Comment by JPH71** [comment]
Dear Josh, - @joshallen13

I was struggling to find how to get to the original urls - luckily @Cody is
a log file hoarder and i noticed the Icons/ in the urls made it all
different - so after stripping them it went back to normal....

but thanks for showing me how to find the pesky URLs behind the code...


Jason xxx

**Comment by JPH71** [comment]
Hear. Hear!

**Comment by CodyBerenson** [comment]
@JPH71 
LOL....that @ isn't me.
