### ISSUE TITLE
Annoying to me, but maybe not to others...

### ISSUE THREAD

**Issue by joshallen13** [CodyBerenson/PGMA-Modernized#63]
I don't understand the Collections feature enhancement you guys just rolled out. I went from having 6 curated collections to over 300 -- mostly with just one movie in them for an actor. I now have to go manually delete each one of these to tidy back up my list.  I reserve these for searching features for actors, studios, and the like, but I know each person has their own preference for library organization and what not. I don't see the added value for this feature, at least not yet. 

I vote to remove this and go back to not using this feature. :(

**Comment by j-ktz** [comment]
I second @joshallen13. I love using Collections, but I take time on mine to add custom poster art, background art and descriptions. This would make things get a bit out of hand for me. Is it possible to make an alternate agent that doesn't include the collections feature? Then we can uncheck the one we don't want to use? Just an idea...

**Comment by joshallen13** [comment]
@j-ktz Since I mostly stick to GEVI for my matches, I went into the python script in the GEVI.bundle and deleted the 1g - Collections section and ran it, seemingly with no issues. I am currently working on utilizing the Collections section much like your amazing Collections page is organized. 

Also, meant to say thanks for letting me view your library! I'm impressed with your content and I think my roommate was too, as he was voraciously consuming lots of it LOL. I apologize if he took advantage of your kindness in sharing your server with me.

**Comment by j-ktz** [comment]
@joshallen13 Thanks! I just re-did some of my collections this weekend including genre collections. Pretty proud of 'em, so want to keep them nice and tidy. Haha, no worries! Glad he got some use out of them. 😉

**Comment by JPH71** [comment]
As it stands it is very easy to put collections as a preference, I remember
mentioning this before but you were not responsive about it.
I will make changes and implement this straight away but leave collections
as per the file name.

What's up with you - for the past couple of days, I feel like you just want
to lash out??? Is someone or summat stressing you out... apart from me?

Jason....
xxx

**Comment by joshallen13** [comment]
> I remember mentioning this before but you were not responsive about it.

What's up with you - for the past couple of days, I feel like you just want to lash out??? Is someone or summat stressing you out... apart from me? Jason.... xxx
> […](#)

In theory I suppose it is not a bad idea, just in practice I am not sure if there is a value to the addition of so many collections where one can create their own collections ad hoc with using a couple search parameters and then making the collection that way. I only had a handful of created collections that had more than one title in it. Others may have a better selection than I though. 

As for the second half of your reply, I’m not sure I’m the one that’s intended for? And if I am, then I am sorry for seeming to be abrasive to you, that is not my intention at all. 

Josh

**Comment by j-ktz** [comment]
He's prob mad at me @joshallen13. Sorry if I missed a note about Collections @JPH71. I love the idea of auto generating collections and think it would be helpful to most folks, just not me since I'm so anal with my Collections. If it's a toggle on/off or a version of an agent we can uncheck in Plex, that would be fine.

**Comment by CodyBerenson** [comment]
Hi Gentlemen, you've done nothing wrong.  That was a response to me privately but looks like some GitHub wires got crossed and voila, you get a glimpse behind the curtain... 

I don't use Collections at all, so testing this aspect was new.  While testing, I raised some concerns, especially for folks with multiple libraries.  Jason suggested that he could make the functionality a preference.  I was indifferent, which in hindsight, was a mistake.  Although I don't use collections functionality, you've both on many occasions discussed your use of collections and I should have advocated for making it an option rather than being indifferent.  You deserve better.  I own this mistake, and I sincerely apologize.

Going forward, I think its a good idea to pull you folks in early to hear about possible enhancements and get your thoughts and feedback.  A user-group of sorts.  

Apologies, once again guys.

**Comment by JPH71** [comment]
Oops!
It was not meant at either of you! I was just replying to Cody and
unfortunately put it in this public email.... my bad...

I am just testing the collection options on AEBN at the moment. So that
everyone has the options to turn them fully off or leave them on.
So there will be 5 options all set to off by default. I will explain the
changes as I introduce the options.
Based on our new format : *(Studio[;IAFD Studio]) - Title (Year).mp4*

   - Studio Collections : If set to ON - A collection called *Studio* will
   be created
      - IAFD Studio - is optional and is used to find the movie on IAFD if
      it is different to the one recorded on your agent. For example
GayHotmovies
      uses Titan Men whilst IAFD uses Titan Media, if you want to get
actors, and
      their roles from IAFD whilst using GayHotMovies, you will have to include
      this option. If using GEVI you can drop it.
      - As you will have noticed Films now show if they have been found on
      IAFD.
   - Title Collections - If set to ON, the agent will split the title into
   as many parts as there are *" - " *in the title. Each of these parts
   generates a collection unless it's the last part and does not end with a
   number:
      - A film like *(Lucas Entertainment) - Bareback Auditions 1 (2014)* will
      create a collection called *Bareback Auditions* whether the website
      has a collection field entry or not. The collection will be created by
      default whether you set this OFF or not if the website has a collection
      entry. This has been default mode since I wrote the agents.
      - A film like *(Lucas Entertainment) - Bareback Auditions 8 - Fresh
      Additions (2017)* will do the same as above as Fresh Additions is not
      part of a series its just a plain title.
      - A Film like *(Spritzz) - Young Bastards 8 - Prison Camp 2 - Anal
      Assault (2013)* would create 2 collections namely Young Bastards and
      Prison Camp.
      - These collections are reverse order, so in the case of  the Young
      bastards film above the collections are saved as Prison Camp, followed by
      Young Bastards. this is to maintain the relationships between
movies in the
      same series.
      - Director Collections - each director listed against a film is added
   to its on collection
      - I found out that directors can have their photos stored just like
      actors, so by default this is done whether this setting is ON or OFF, if
      you search by director now, if he has a photo on IAFD, their picture will
      show just like actors rather than their Initials
   - Cast Collections - If set to ON, each individual actor will be added
   to a collection
      - Actors' thumbnails are marked with a green tick as standard if:
         - If the film is found on IAFD
         - or is not found on IAFD but the actor
         - or the actor is on the Agent website but not on IAFD
      - If the actor has an Alias/ AKA Name it is also picked up.
      - If the film has the actor's role recorded, the role will overwrite
      the Alias/AKA Name.
      - An actor's thumbnail will only be marked with a red cross if he is
      not found on IAFD.
      - Genre Collections: If set to ON they will be picked up.

This collection malarkey started because I wanted to improve Film Matching,
GEVI which Cody introduced to me has become a firm favourite, but it has
one niggling issue: it mixes its titles up even within a series. So for
example you get entries like these:

   1. Barebacking Businessmen, Gentlemen 13
   <https://www.gayeroticvideoindex.com/V/4/53584.html> whilst on AEBN it
   would be Gentlemen 13, Barebacking Businessmen, if anything happened to
   GEVI you would have to rename your files to the AEBN style to match it.
   This is not always the case as GEVI also records loads of films in the same
   format as AEBN.
   2. Sometimes an Agent website will miss out the Gentlemen 13 bit - it
   will now match as the matching is performed on the barebacking business
   part if you name the movie in the AEBN format. if you have title
   collections set to ON, the movie will note that it is in the Gentlemen
   collection. This means that if you find a movie like Servicing the CEO
   which is in the Gentlemen series but not on GEVI, but is recorded on
   another agent website without the Gentlemen series as this movie is on
   Gayworld, it will still be put into the collection.
   3. So if you stick to the AEBN style whether you include a 1 for the
   first in a series or not the film will be matched correctly whether it's on
   GEVI or not.

Whilst implementing this I saw messages on collections and went extending
the functionality without thinking of the consequences to those who don't
use them..... if I could take my own foot off I'd kick myself!

I hope this explains my reasoning well, once the corrected agents come out,
you will have the option to turn off collection gathering. But have the
option of naming your files correctly and matching them against all agents
so long as the are named in this format *(Studio[;IAFD Studio]) - Title
[{Series - short title order}] (Year).ext*

It will take me a day or two to implement these changes. After you rescan
your movies the collections will be removed. You will, however, have to
delete all the empty collections, at least Plex allows you to do this
easily as you can multi-select.....

Cheers and my apologies once again especially to Cody who re-tests all my
changes... and understandably feels like someone has pissed in his morning
coffee!

Jason xxx

**Comment by joshallen13** [comment]
I'm so glad that it should be an easy fix to include or exclude based on user preference this feature. I am beyond thrilled about the improvements you've incorporated, and it would be nice to know what your end goals are in terms of product/project roadmap to identify areas where we as users are hoping it follows. I'd hate to see you pour tons of work into something that doesn't really add value.  I say this because I'm guilty of being the guy who works endlessly on something just because I can, when I should ask myself if I should. 

Thank you for being open to the comments we've provided, and I hope you two work out what is going on behind the curtain :P

**Comment by CodyBerenson** [comment]
> it would be nice to know what your end goals are in terms of product/project roadmap to identify areas where we as users are hoping it follows. I'd hate to see you pour tons of work into something that doesn't really add value.

@jph71 my hand is on a bible when I tell you that I swear to god that in no way I gave @joshallen13 these words to say...even though they are identical to my words....multiple times over.  

LOL LOL LOL LOL LOL LOL LOL 

My side hurts from laughing!

**Comment by JPH71** [comment]
I know.... it's almost the clone machine.... but i do have a tendency to go
into tunnel mode and then the thought pops in... wtf am i doing this?

LOL
