### ISSUE TITLE
Updates to PGMA guidance re: Creating Poster Art for Scenes and Films with No Cover Art, Populating Roles, and Collections Functionality

### ISSUE THREAD

**Issue by joshallen13** [CodyBerenson/PGMA-Modernized#65]
Came across this site while looking for a suitable collection cover poster, and found it very simple and easy to use--AND QUICK!

[Coverlabs](https://www.coverlabs.io)

Thought I would share for those who wish to create something visually appealing for the file thumbnail rather than a blurred auto-generated ambiguous thumbnail. Just a few steps to create awesome content:

1. Select your template.
2. Insert your Title
3. Drag an Image
4. Resize
5. Download
6. Upload to your Plex Library entry

Et voila!

**Comment by CodyBerenson** [comment]
Will do.  Much appreciated!

**Comment by CodyBerenson** [comment]
@joshallen13 

Do you mind taking a look and providing feedback?  Thanks!

[Coverlabs.pdf](https://github.com/CodyBerenson/PGMA-Modernized/files/6050668/Coverlabs.pdf)

**Comment by CodyBerenson** [comment]
@jph71 

Here is the draft update to the guide re: Populating Cast Roles.

[Roles.pdf](https://github.com/CodyBerenson/PGMA-Modernized/files/6050955/Roles.pdf)

**Comment by CodyBerenson** [comment]
@JPH71 @joshallen13 @J-KTZ 

Here is the draft updates to the guide re: Collections.  

[Collections.pdf](https://github.com/CodyBerenson/PGMA-Modernized/files/6051496/Collections.pdf)

I'm not a Collections user.  Please review/provide any feedback.

**Comment by JPH71** [comment]
Those look good!

**Comment by j-ktz** [comment]
@CodyBerenson These guides are EPIC. You boys are putting in WORK. Appreciate you all! Let me know if I can contribute in any way :) Love the Collection options @JPH71  🙌

**Comment by JPH71** [comment]
Cody is a fucking wordsmith par excellence... And surprise - he uses
american english! Wee dig there @CodyBerenson.

Jason!

**Comment by joshallen13** [comment]
> @JPH71 @joshallen13 @j-ktz
> 
> Here is the draft updates to the guide re: Collections.
> 
> [Collections.pdf](https://github.com/CodyBerenson/PGMA-Modernized/files/6051496/Collections.pdf)
> 
> I'm not a Collections user. Please review/provide any feedback.

My one comment would be the mention of "Creating a Collection based on Film Title." Is there an easier way to say that without having to explain it as is currently done below the picture? Perhaps, "Create Collection based on Film Series" or the like? When saying Film Title it sounds like you would create a collection based on a word within the title... unless that is the function and I'm not clearly interpreting the use case.

**Comment by joshallen13** [comment]
> @JPH71
> 
> Here is the draft update to the guide re: Populating Cast Roles.
> 
> [Roles.pdf](https://github.com/CodyBerenson/PGMA-Modernized/files/6051040/Roles.pdf)

 I think it would be really helpful to articulate in a sentence or two at the beginning of this section what it is this feature is bringing to the table. I will admit I was really confused with the addition of IAFD to the studio naming, and it could be confusing to the newcomer. I would maybe preface it with this being an optional route to take for those wanting more information. Sort of like an "advanced settings" level for matching.

**Comment by joshallen13** [comment]
> @joshallen13
> 
> Do you mind taking a look and providing feedback? Thanks!
> 
> [Coverlabs.pdf](https://github.com/CodyBerenson/PGMA-Modernized/files/6051004/Coverlabs.pdf)

This looks great! I guess I did a good job explaining it, as you basically used my words to write it LOL

Is there a capability in this GitHub project for us to make a library of poster art to compile and share the created content for posters? I know @j-ktz does an awesome job making his, and could be a really fun way to collaborate and curate with one another. Just an idea, not sure how that could work....

**Comment by CodyBerenson** [comment]
@joshallen13 I not only used your words in the write up, I followed your instructions to create the screengrab. :)

GitHub has rules of behavior about inappropriate content. I’m a little paranoid about graphic graphics, so to speak. They already took our site down once...we went dark for a week (and it wasn't related to inappropriate content at all). Best to share that privately I think.

**Comment by joshallen13** [comment]
Noted and completely understand. I wonder if there's an interest in creating a Google Drive bucket or something similar to post these, rather than here. Does anyone have a suggestion on the platform that would work best for multi-user collaboration? I'm happy to host that, if that is an issue.

**Comment by JPH71** [comment]
@JoshAllen13 - I can see your point, that though briefly fluttered in my
mind... but we have used Film Title in the naming format so I stuck to that
as the title covers everything.... let's see what Cody decides and I will
make a quick change to the preferences...

Jason

**Comment by CodyBerenson** [comment]
um. @JPH71 please reread what Josh is asking. i think you may have entirely misunderstood.   ;)

**Comment by j-ktz** [comment]
@joshallen13 @CodyBerenson Totally willing to help or share what I've created so far. Don't think TPDB would be too happy about my works of art either. Google Drive or Dropbox might work?

**Comment by JPH71** [comment]
I am sure I read an email on here where @JoshAllen13 mentioned the word
Film Series - that was what I was replying to!

Just finished GayWorld and GayMovie - sending them! after a quick initial
test...

**Comment by j-ktz** [comment]
This is SUPER nit-picky but is it possible to move the Roles legend to the bottom of the summary? Otherwise, you have to click Read More, to see the first line of the Summary because the legend takes up all the space. Imo, I think the scene/movie summary is more helpful since the legend is the same every time. Not a priority.

**Comment by joshallen13** [comment]
> um. @JPH71 please reread what Josh is asking. i think you may have entirely misunderstood. ;)

@CodyBerenson I'm curious to hear what you think I'm referencing here, as @JPH71's reply was pretty close to the answer I expected. Given his reply, he's looking to you to. approve my verbiage change in the agent preferences checkboxes area, specifically for the Collections created by using Film Titles, but more closely depicted by collections created based on a Film Series. 

Hopefully my man-splaining didn't step on any toes!

**Comment by CodyBerenson** [comment]
@joshallen13 I don't think any of you want to hear what i'm currently thinking.

**Comment by joshallen13** [comment]
Hopefully it's not ill thoughts towards us for being vocal with our critiques. Please let us know what the vibe is, as I'm kind of lost right now. It's hard to read the room online, especially with so many different threads on one page.

**Comment by j-ktz** [comment]
![tenor-1](https://user-images.githubusercontent.com/59346628/109373382-67f02000-787c-11eb-8380-47cdfbe07f13.gif)

**Comment by CodyBerenson** [comment]
> @CodyBerenson In the Roles documentation it states you can put both Studio names ((Studio;IAFDStudio) - Title (Year).ext.) but can you also do this with scene names? For example, what if the scene name is different on IAFD than WayBig, but you wanna use WayBig for the poster art and description but IAFD for roles and cast... possible?

Eventually.  Because there are so many agents...in fact, a constantly ever, ever, ever, ever increasing number of agents, propagating enhancements through the agents is a) time consuming and b) easily side tracked with every new tweak or whim.  So, niche agents that likely are never used by anyone such as WolffStudios and GayWorld have the enhancements, but workhorses such as WayBig have not yet.

**Comment by JPH71** [comment]
The new functionality is in 2 files - genfunctions and iafd - these work
the same for all agents. so you can do this - (Studio;IAFDStudio) - Title
(Year).ext.
Guys wait - I can not rush through all the agents at once... waybig needs
some extra work to get it to match some peculiarities - the niche ones were
easy to convert so got done... even though i was doing my best to do them
in alpha order....
These have been done:

   1. AdultFilmDatabase.bundle
   2. AEBNiii.bundle
   3. AVEntertainments.bundle
   4. BestExclusivePorn.bundle
   5. CDUniverse.bundle
   6. Fagalicious.bundle
   7. GayDVDEmpire.bundle
   8. GayFetishandBDSM.bundle
   9. GayHotMovies.bundle
   10. GayMovie.bundle
   11. GayWorld.bundle
   12. GEVI.bundle
   13. WolffVideo.bundle

I am left with these:

   1. GayRado.bundle
   2. HomoActive.bundle
   3. IAFD.bundle
   4. nymMedia.bundle
   5. QueerClick.bundle
   6. RadVideo.bundle
   7. WayBig.bundle

Waybig and IAFD will be done last - IAFD as it works differently to the
other agents, and WAYBIG because of the aforementioned issues.

I will also put in the option to use the Legend at the front or at the end.

When I started this exercise in December..January - Plex gave more screen
real estate to the summary so it did not really matter.
So I will put in the option tomorrow and send them to @CodyBerenson

I am off to bed - it is 05h00 hours here......

Night Everyone.....
