### ISSUE TITLE
Fagalicious - Unable to match

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#66]
I can't get these two titles to match. Any ideas? 

https://fagalicious.com/iconmale-adam-ramzi-tristan-hunter-daddys-weekend-scene-4-hot-for-teacher/

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6052661/com.plexapp.agents.Fagalicious.log)

https://fagalicious.com/gaycest-myles-landon-ian-levine-breeding-my-little-boys-hole-tape-8-working-from-home/

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6052681/com.plexapp.agents.Fagalicious.log)

**Comment by CodyBerenson** [comment]
I get the same results.

@jph71
Can you look into these while you're working to resolve the lower case issue as well?  That way we can close both these issues together.  Thanks.

**Comment by JPH71** [comment]
I have just finished a correction to fagalicious - i will look at this and
then send it with the current fix to @codyberenson.
Give me half an hour or so!

**Comment by j-ktz** [comment]
@CodyBerenson I always forget the bug tag. Ty for always adding. 😜 

@JPH71  YOU ARE A SAINT.

**Comment by JPH71** [comment]
Hi Cody

I am just about to send the fixes.
I noticed another error in @J-Ktz 's log file - easier to show a segment of
his log:
2021-02-26 16:51:24,531 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - SEARCH:: File Name             : (IconMale) - Adam Ramzi barebacks
Tristan Hunter in “Daddy’s Weekend, Scene 4 - Hot for Teacher” (2021)
2021-02-26 16:51:24,531 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - SEARCH:: File Folder           : /volume2/torrents/New Porn/IconMale
2021-02-26 16:51:24,532 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 -
------------------------------------------------------------------------------
2021-02-26 16:51:24,559 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: Collection            : ['Adam Ramzi barebacks Tristan Hunter
in "Daddy\'s Weekend, Scene', 'IconMale']
2021-02-26 16:51:24,560 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: CompareDate           : December 31, 2021
2021-02-26 16:51:24,560 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: CompareIAFDStudio     :
2021-02-26 16:51:24,561 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: CompareStudio         : iconmale
2021-02-26 16:51:24,561 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: CompareTitle          :
['4aaaaaaaabbcccdddddeeeeeeeeefhhhiiikkmmnnnnnoorrrrrrsssstttttuwyz', '
aceefhhoorrtt']
2021-02-26 16:51:24,562 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: Compilation           : No
2021-02-26 16:51:24,562 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: FoundOnIAFD           : No
2021-02-26 16:51:24,562 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: IAFDCompareTitle      :
['4aaaaaaaabbcccdddddeeeeeeeeefhhhiiikkmmnnnnnoorrrrrrsssstttttuwyz', '
aceefhhoorrtt']
2021-02-26 16:51:24,563 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: IAFDSearchTitle       : Hot+for+Teachera
2021-02-26 16:51:24,563 (7fe55da11700) :  INFO (sandbox:19) - Fagalicious
 - GENF  :: IAFDShortTitle        : Adam Ramzi barebacks Tristan Hunter in
"Daddy's Weekend, Scene 4 - Hot for Teacher"

As J-KTZ is not using windows - the last " got encoded as an 'a'. This last
apostrophe shouldn't be there in the first place, so I have made a change
to genfuntions.py to strip punctuation marks at the end. This has been
copied through to all the agents as it would have interfered with a search
on IAFD.

The error J-KTZ was a first grade or in old money "Standard 1" error, I
counted starting with 1 rather than 0!

The lower case issue was already sorted - so will be included in the zip I
am sending you.

Guys keep hammering by throwing as many weird titles... each website uses a
different set of rules which change from time to time... as we recently
discovered Best Exclusive has shortened its search string from 60
characters to 50.

With these enhancements, I have improved on Logging to make it easier to
identify the issues!
@CodyBerenson you will have all the agents in another 5-10 minutes

Jason xxx

**Comment by CodyBerenson** [comment]
@JPH71 the third time is the charm. this update fixed the issues. 

@j-ktz corrected bundle will be pushed to GitHub in a moment. before using, please triple check to make sure the collections settings are off, if that is your preference. cheers

**Comment by j-ktz** [comment]
@j-ktz @CodyBerenson Thank you porn angels. 🙏

**Comment by JPH71** [comment]
This song straight away started playing in my mind
https://www.youtube.com/watch?v=41GsS3jldOI&ab_channel=GlaucoMalagoli

porn instead of earth!

Jason xxx

I have updated GayWorld and GayMovie as they are closely related to
GayFetishandBDSM - I noticed that some titles - scraped the cast field and
did not strip the initial colon as in these titles the *:* was followed by
*&nbsp;* instead of space....
Correction made to all three and also an initialisation error if there was
no synopsis.... GayWorld also only took the first paragraph of the
synopsis.....
All tested working

Here they are

https://drive.google.com/file/d/1_hA9fmWM4qiZxuIWnx2B06wXDJ13XC9i/view?usp=sharing


Jason xxxx

**Comment by j-ktz** [comment]
These are now matching but Fagalicious doesn't seem able to pull in the posters. I've just been grabbing the URLs and using the image cropper in the meantime.

**Comment by CodyBerenson** [comment]
posters worked for me

**Comment by CodyBerenson** [comment]
@j-ktz logs please

**Comment by j-ktz** [comment]
Attached!

[com.plexapp.agents.Fagalicious-1.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6053562/com.plexapp.agents.Fagalicious-1.log)

**Comment by JPH71** [comment]
there is an error in the code... but it seems thumbor failed to crop the
image first

**Comment by JPH71** [comment]
I have checked the code and Thumbor is definitely failing - from that point
it does not set the picture content and eros - you should instead have
ended with an uncropped image...
i will look at this
By the way - all of you - do not download the code I mistakenly sent on
here till Cody has downloaded it and posted it to the
repository after secondary tests!

**Comment by CodyBerenson** [comment]
@JPH71 
Just checked, Thumbor is definitely up (for only two more months, by the way).  Probably not what you meant.  Just wanted to confirm.  And, oh by the way, we only have image cropping for two more months in case I haven't mentioned.

**Comment by JPH71** [comment]
It will mainly affect those who are using effing mackintoshes...
Better write a small "How To" on setting up a Thumbor service for the guys

Jason...

night xxx

**Comment by CodyBerenson** [comment]
> Better write a small "How To" on setting up a Thumbor service for the guys

Ok, you can take that assignment.  Thumbor is meant to run on unix.  It won't run on anything else.  Hence why I installed in to GCP, and hence why we need to remove it as a dependency #20 and not think folks who are struggling to understand how to set up/configure our agents in PMS are going to be able to establish a Thumbor service.

**Comment by JPH71** [comment]
Oh shite! Unix!

Well - I have windows and there is that new service for posters that I
think Josh found - that can stand in for those who are using mackintoshes
until i figure a way out...
or find a unix script to do what the vbscript does on windows...

Jason x

**Comment by CodyBerenson** [comment]
Um....look over there.

**Comment by JPH71** [comment]
where??
