### ISSUE TITLE
Plex Movie Scanner, Plex Video Files, Plex Video Files Scanner

### ISSUE THREAD

**Issue by mstrchris83** [CodyBerenson/PGMA-Modernized#7]
Hello, can you help me? When choosing the agent in the library setup window, when it asks for scanner, which scanner option should I choose? Plex Movie Scanner, Plex Video Files, or Plex Video Files Scanner.

I'm not sure which one works/works best with this. Thank you!

**Comment by CodyBerenson** [comment]
Hello @mstrchris83 

Choose Plex Movie Scanner. Let us know if you have any more questions. Cheers.

**Comment by JPH71** [comment]
Hello @mstrchris83
Then after choosing the plex movie scanner you have three options depending on your library's content:

1.  For video scenes - use gay adult scenes agent
2. For full movies - use gay adult films
3. For a mixture - use gay adult

happy to help

**Comment by mstrchris83** [comment]
Thanks guys!

**Comment by JPH71** [comment]
You are very welcome...
Do let s know if there is any particular website or blog you will like to
be added to the scrappers, and hopefully we will be able to write an agent
for it!

**Comment by JPH71** [comment]
@mstrchris83 

Did you get the scrappers to work?

Jason

**Comment by CodyBerenson** [comment]
@mstrchris83 

Github mistakenly took the repository down for almost a week, so you may have needed help and we weren't here.  All good?

**Comment by j-ktz** [comment]
@CodyBerenson I saw in the screenshot on the Code page that you have a different library set up for each studio. What's the thinking behind this? Just looking at other ways to organize so wanted to hear your best practices.

**Comment by CodyBerenson** [comment]
@j-ktz 
Hi!  Hope you're doing well and staying safe!  This is a long-winded rambling response.  Hope it helps.

Here's why I do it (separate studios for scenes)...by NO means is it a best practice. Its all about the journey.  Long, long, long before there was Plex, I was hording porn and for organization sake, for YEARS i separated my collection into studios, with films at the root folder for each studio and scenes in a Scenes subfolder. Then, I discovered Plex for my family's movie and TV collection.  LOVE IT.  So, I scoured the net to see if there was a way to index Gay Porn, and found an AEBN agent.  AEBN indexed films, but not scenes that aren't part of a film.  Lucky for me, Plex (at least the Windows version) doesn't scan any folder called "Scenes", so I was able to start building my films library without un-indexed scenes cluttering it up.  I was happy as a lark.  Then @JPH71 came along with his WayBig agent.  Until then, I never considered indexing scenes....and didn't know about Blog sites with their DVD-like covers.   So, I would either need to rename all my Scenes folders (because as I said Plex won't look at them), or, create separate Libraries.  I created a TimTales Library.  Loved it.  Moved on to SeanCody, Men.Com, NextDoor, etc.  

My libraries are pretty large.  My Films library (12,000 and counting) and scenes libraries (several have 1000+).  For me, commingling them would be a nightmare at scan time.  

So, I'd say I lucked into my approach because I've been at this for quite a while.  ;) 

Take care!  Let me know if this does or doesn't make sense.

xoxo

**Comment by JPH71** [comment]
@codyberenson
The original AEBN which I adapted also did scenes, but when I adapted it, I
took the scene parts out as the only scenes I collected were not the ones
from movies... Hence why it's called AEBNii.. also it only sort of scrapped
2% of the movies...
The original should be still out there somewhere...

**Comment by CodyBerenson** [comment]
@JPH71 

why the hell would anyone want the original.  it is buggy, will only match the first when multiple movies have the same title, and doesnt return actor pics. thats insulting to all your hard work. go sit in the corner

**Comment by j-ktz** [comment]
@CodyBerenson That makes a ton of sense. I'm no where near your level but slowing working that way (at 1,500 titles) so we'll see what the future hold as far as organization. Can't thank you and @JPH71 for all your hard work. My life has been changed. Hope you boys are staying safe and healthy!

**Comment by JPH71** [comment]
I better buy a dunce cap too...
If you would like I can look at the old code and see about scrapping scene
information as gaydvdempire and gayhotmovies also show scene information...
we can give this as a ticked preference, if the user wants this it the
filename will have to have a definite format (Studio) - Title (Year) - Sc.
<number> - <List of Actors>.ext where the number would have to be included,
list of actors can be optional??? - if AEBN, GayDVDEmpire and GayHotMovies
asre then added to the GayAdultScenes scrapper if the file does not conform
to this extended format they will not scrape....

And we can update the summary information to have the scene information
included like GEVI's as standard
that is to say it picks the usual summary and then below it shows the scene
information together with the actor names if they are on the movies page in
the site...

Let me know what you think

Jason
