### ISSUE TITLE
Poster image is not fetched

### ISSUE THREAD

**Issue by vampirelayer** [CodyBerenson/PGMA-Modernized#99]
I'm able to match these titles and fetch all meta data **except** the poster image.

Just to name a few:

`https://fagalicious.com/hothouse-ryan-rose-pounds-darius-ferdynand-in-gutter-punks/
https://fagalicious.com/falcon-studios-brent-corrigan-darius-ferdynand-flip-fuck-poolside-1/
https://fagalicious.com/falcon-studios-sean-zevran-fucks-shawn-wolfe-crave/
https://fagalicious.com/belami-kevin-warhol-and-andre-boleyn-double-fuck-manuel-rios-bareback/
https://www.queerclick.com/qc/2016/11/cockyboys-alex-mecum-fucks-carter-dane.php`

**Comment by CodyBerenson** [comment]
@vampirelayer 
Greetings.  These retrieve the poster image for me.  

Question:  Did you update your agents to the latest code?  The scene agents use a Thumbor instance to crop images, and the cloud hosting for the Thumbor instance changed URLs a week or two.  The correct thumbor address is in each scene agent's settings:

![image](https://user-images.githubusercontent.com/40373801/118266027-078a7b00-b488-11eb-8b5f-260eff739ec7.png)

If you are using the correct thumbor address and have verified poster isn't among the poster art for the title, please attach your fagalicious log file.  Jason won't be able to trouble shoot without your log file.

![image](https://user-images.githubusercontent.com/40373801/118266379-7a93f180-b488-11eb-960d-1dded651157b.png)

**Comment by vampirelayer** [comment]
You're right. I forgot to install the latest plugins.
The posters now appear, but do I have to manually set it in Edit mode?
I don't remember having to do that previously.

**Comment by JPH71** [comment]
@Cody - just to let you know that the new Thumbor is not working for me...
It pulls down the image but fails on thumborising....

could you check your logs to see if you have the same issue? Should be
right at the end of the update section.

I updated bestexclusive and queerclick yesterday... will test tonight

I will send you the logs when I get home tonight.... another 12hr shift
today

**Comment by CodyBerenson** [comment]
@JPH71
LOL.  You keep doing this....you have to @ with the proper github username, not from the first name that appears in your email.  Poor Cody, whoever that user may be, is now wondering why Thumbor isn't working for you.  LOL LOL LOL.  Perhaps he's interested in scraping male porn so alls well, that ends well.  LOL.  

The cropping works perfectly for me.  Both for new titles to match and as I'm cleaning up (fix match) old titles that were pre-cropping.   

Try it in a browser using an image that wouldn't be in your computer's cache (I always find the latest posts on the blogs to test with)

http://34.68.158.72:8888/unsafe/0x0:1200x800/<URL> 
and play around with the dimensions  
or
http://34.68.158.72:8888/unsafe/0x0:1000x1500/filters:rotate(90)/<URL>
and play around with the rotation

that may help us understand if these just don't work for you inline, even from a browser, and it may be IP related since you're in Europe...or....

**Comment by CodyBerenson** [comment]
@JPH71 
I just VPN'd into Madrid, and tested the very latest title from WayBig, which is a good test because the Bel Ami title has an 800 x 1844 image poster.  The agent/thumbor properly cropped the poster to 800 x 1200, same as the thumbor manual call would return:

http://34.68.158.72:8888/unsafe/0x0:800x1200/https://zing.waybig.com/reviews/BelAmiOnline/05-14-21/jerome-exupery-robin-rief-belamionline-01.jpg

**Comment by JPH71** [comment]
@CodyBerenson I will check in an hour when I get back home... I may be
seeing things... just finishing  another long shift and it feels like my
eyes are a-wobbling in my head...

**Comment by CodyBerenson** [comment]
Relax your eyes and prepare for ESC next week.  Both semi-finals and the grand final!

**Comment by JPH71** [comment]
Both these links give me a 504 error - took too long to respond...
I have tried both in Chrome and edge


Jason

**Comment by CodyBerenson** [comment]
are you using vpn?  can you try a different vpn server or a different device on a different network?

**Comment by JPH71** [comment]
Unfortunately, if I use my VPN whilst I am in Belgium, I get kicked off my
server in England.... grrrr
I will have to test this when I get back....
Any other European residents who can confirm its working for them???

**Comment by cody** [comment]
> @JPH71
> LOL. You keep doing this....you have to @ with the proper github username, not from the first name that appears in your email. Poor Cody, whoever that user may be, is now wondering why Thumbor isn't working for you. LOL LOL LOL. Perhaps he's interested in scraping male porn so alls well, that ends well. LOL.
> 
> The cropping works perfectly for me. Both for new titles to match and as I'm cleaning up (fix match) old titles that were pre-cropping.
> 
> Try it in a browser using an image that wouldn't be in your computer's cache (I always find the latest posts on the blogs to test with)
> 
> http://34.68.158.72:8888/unsafe/0x0:1200x800/
> and play around with the dimensions
> or
> http://34.68.158.72:8888/unsafe/0x0:1000x1500/filters:rotate(90)/
> and play around with the rotation
> 
> that may help us understand if these just don't work for you inline, even from a browser, and it may be IP related since you're in Europe...or....

Ha! I love the fact that I’ve been brought into this. If I had any applicable skills, I’d be happy to help troubleshoot this porn thumbnail scraper. Unfortunately, I’ll have to let @CodyBerenson handle that.
